### ISSUE TITLE
Gitter support?

### ISSUE THREAD

**Issue by jleclanche** [reactiflux/discord-irc#100]
This is a long shot, but I also use [gitter-irc-bot](https://github.com/finnp/gitter-irc-bot) which, unlike discord-irc, doesn't support multiple inputs and outputs and doesn't have a bunch of the discord-irc protocols.

If the IRC and Discord logic aren't mixed too much, adding support for gitter based on the gitter-irc-bot code (MIT, also in js) shouldn't be too hard. Thoughts?

**Comment by ekmartin** [comment]
No, shouldn't be too hard to change the code base to support gitter instead. I don't have time to do it at the moment though, but if you're interested feel free to use this (or slack-irc, linked below) code as a starting point :)

This is based on https://github.com/ekmartin/slack-irc - which is pretty similar but have enough differences that I felt they warranted separate projects.

**Comment by jleclanche** [comment]
@ekmartin Would you take a PR for it if I worked on it at some point?

**Comment by ekmartin** [comment]
I think it would be better suited as its own package. There's a lot of Discord specific quirks here that wouldn't matter for Gitter and vice-versa, so I think trying to support both with one project would make things a lot more complicated than they would need to be.

**Comment by jleclanche** [comment]
Hm, real shame, I think a "generic" two-way-mirror type of bot (with pluggable backends of sorts) would be incredibly valuable. Theoretically you could set up mirrors between, for example, slack and discord or do a three way mirror between multiple backends ... :)

But I can understand if you don't want to have to maintain that.

**Comment by ekmartin** [comment]
Definitely would be cool. Could make a sort of core that is installed in slack-irc, discord-irc etc. - as to still be able to maintain backwards compatibility with the existing applications.

However, this would really be more of a new project that reuses some of the code. I don't think I've got enough time right now, but it's definitely a refactor that would be useful to do in the future.

If you're interested in working on a Gitter bridge you could start by just reusing one of the existing code bases, and then if we manage to refactor the core functionality into a separate package later on the different bridge projects can be changed to use that.

**Comment by jleclanche** [comment]
I tried a couple of prototypes a while back (in python and in go - https://github.com/jleclanche/gitterway), but then realized I'd never have the time to make it happen by myself :/
