### ISSUE TITLE
Direct Messages from IRC to Discord Channel

### ISSUE THREAD

**Issue by Aim23** [reactiflux/discord-irc#101]
Hi,

would it be possible to add a feature to activate that mentioned title issue?
I would like to use direct message at the irc level and present this into a discord channel. 

thanks in advance.

**Comment by ekmartin** [comment]
No, that's not possible in the bots current state. I don't think it's something that fits well with the main goal of the project either, but it shouldn't be too hard to implement in a fork if you're interested in that.
