### ISSUE TITLE
Removing nicknames of other IRC bots

### ISSUE THREAD

**Issue by acffordyce973** [reactiflux/discord-irc#103]
I am using this relay in an IRC channel which is full of other relay bots. What would be the best way to remove the nicknames of these bots but keep their messages?

Example:
Currently it shows on Discord as: <RelayBot> <ACF> This is a test
I want to remove the <RelayBot> and keep the rest as so: <ACF> This is a test

**Comment by jamie** [comment]
@acffordyce973 github ate your angle brackets.

**Comment by ekmartin** [comment]
Hi @acffordyce973. Sorry for the late answer. I don't think a solution for this is something that would need to be in discord-irc itself, as it's a pretty specific use case. I implemented it in [this branch](https://github.com/reactiflux/discord-irc/commit/1068c79445852f822e072cd36d09c18bb1751bfa) though, so if you want to you can go ahead and fork this repository and use that branch.

For instructions on how to run that specific branch see https://github.com/reactiflux/discord-irc/issues/135#issuecomment-252521236. To use the example I linked, add `"removeNicknameUsers": ["bot1", "bot2"]` to your config.
