### ISSUE TITLE
what is /path/to/config.json?

### ISSUE THREAD

**Issue by YuyQuan** [reactiflux/discord-irc#109]
This part of the installation guide isn't specific enough.

**Comment by ekmartin** [comment]
It just means wherever you choose to place your config file, i.e. so if you're in the same directory and your config file is named `cool-config.json` it would be `discord-irc --config cool-config.json`. If you're up for it a pull request clarifying it would be nice :)

The config file itself is documented under [Configuration](https://github.com/reactiflux/discord-irc#configuration), as you probably saw.

**Comment by YuyQuan** [comment]
Hi I'm still having troubles setting up my bot.
While this isn't too related to the original thread, I think it's more of an issue with me not setting things up correctly. I'd like to get this up and running and add a more detailed guide for people like me who are going through setting up a discord bot for the first time.

First I'm on Windows 10.
Here's what I did:

`npm install -g discord-irc`
Then I made config.json on my desktop, for simplicity sakes.
Here is my config.json
```
[

  {
    "nickname": "yQuan",
    "server": "irc.freenode.net",
    "discordToken": "A long string of a token",
    "channelMapping": {
      "#other-discord": "#linux"
    }
  }
]
```
Then while at the directory of my desktop invoked the command
`discord-irc --config "config.json"`

At this point the command line is captive; I can't use that command line without ctrl + C'ing

I have another irc client (Hexchat) open. It confirms that "yQuan" has [joined](http://i.imgur.com/E2x8Zoa.png)

However, the messages are not sent or received. Here is a screenshot of what my discord looks [like](http://i.imgur.com/sPEHTGQ.png)

Have I done things correctly?

**Comment by ekmartin** [comment]
Are you using the latest version of the bot? Discord changed their API recently, so the newest version of discord-irc is required.

**Comment by YuyQuan** [comment]
Yes

**Comment by YuyQuan** [comment]
Could it possibly be the string for discordToken?
I've been using [this](http://i.imgur.com/0ARrLRt.png)

I believe that's correct, though, as it doesn't give me a authentication error.
Does everything else I've provided look in place?

**Comment by ekmartin** [comment]
Could you try with version 2 of discord-irc? It upgrades discord.js, and fixes a few weird bugs. Also make sure you follow the guide for how to get a token here: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
