### ISSUE TITLE
Only works discord>IRC, not in reverse

### ISSUE THREAD

**Issue by Scuba95** [reactiflux/discord-irc#110]
Bot no longer relays messages from IRC to the discord, but works in the other direction.

**Comment by ceejayc7** [comment]
+1, just starting seeing this today as well.

**Comment by joshstar** [comment]
+1 Just started today for us too 

![bot](https://cloud.githubusercontent.com/assets/7507582/18375218/0e57f6e4-764c-11e6-89d8-a147b1d715d1.jpg)

**Comment by FrostTheFox** [comment]
Can confirm, just happened to me, restarted IRC network, etc, in fact, it's stopped working entirely for me after being 1 way for a little while.

**Comment by FrostTheFox** [comment]
npm reinstalls don't seem to help, remaking config, etc.

**Comment by ekmartin** [comment]
Discord changed their API so that all bot tokens now need to be prepended with `Bot`. Added a small patch that does this automatically, released in version 1.0.2

**Comment by Scuba95** [comment]
Issue still present after update

**Comment by ekmartin** [comment]
@Scuba95, please see https://github.com/reactiflux/discord-irc/issues/111#issuecomment-246000080.
