### ISSUE TITLE
running but not working

### ISSUE THREAD

**Issue by DracoZaroff** [reactiflux/discord-irc#113]
Updated from version 1.0.1 to 1.0.3. It runs with no errors or messages of any kind but bots do no connect on either IRC or Discord.
update: It picks up what is being said in IRC even though the bot is now showing there but says that the bot is not in the discord channel.
info: Tried to send a message to a channel the bot isn't in:  #discord_channel

**Comment by ekmartin** [comment]
Duplicate of #112
