### ISSUE TITLE
Suppress discord username in irc

### ISSUE THREAD

**Issue by jamie** [reactiflux/discord-irc#114]
I'm wanting to using this project to use Discord as an irc client, in a private discord server all alone by myself.

It'd be awesome if there were a config switch to suppress my nick when posting messages over to IRC (since I'm already using my nick for the bridge).

**Comment by jamie** [comment]
If I can find the time in the next week or two, I'll see if I can do up a PR for this, but if someone beats me to it I won't complain :)

**Comment by SeanMooney** [comment]
i had a similar taught of using discord as my irc client via a privat server.
through im also going to reach out to the opensource project i work on and see if they would
be ok with a general bot for a public discord server too.

**Comment by ekmartin** [comment]
Hi! I understand why you want to do this, but I think it ruins the scope of the project by trying to make it works as a personal IRC client as well. If you wanted to do this you'd be able to make it *much* better by using this project as a base, and heavily extending it for use with only one user instead. You could for example implement support for private messages, commands and so on.

I wrote a bit more about it here: https://github.com/reactiflux/discord-irc/pull/12#issuecomment-156758604

Sorry!
