### ISSUE TITLE
Bot randomally disconnects from IRC

### ISSUE THREAD

**Issue by djyumene** [reactiflux/discord-irc#117]
The IRC bot randomly disconnects from time to time and I'm not sure what's causing it since I only see this:

[19:00] \* +ER-Discord Quit (Client exited)
[19:00] \* ER-Discord has joined

It's not a server issue since the server is fine and is not having memory or bandwidth issues.

**Comment by soundslikecrisps** [comment]
Getting this also. The process is still humming along on the machine but disconnected from IRC.

Would be super nice if it said in Discord/IRC if it has lost the other connection, and possibly why.

**Comment by ekmartin** [comment]
Sorry for the late answer. Have any of you experienced this recently? node-irc is supposed to handle reconnects when `retryCount` is set, which [it is](https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L57).

**Comment by ekmartin** [comment]
Gonna close this in hopes that `retryCount` fixed it. Let me know if it still persists.
