### ISSUE TITLE
Using 'channel' name, not 'global' Discord username

### ISSUE THREAD

**Issue by djyumene** [reactiflux/discord-irc#118]
I saw a topic similar to this back in August when Discord had made it possible to change your name per server/channel you are on. 

Re: https://github.com/reactiflux/discord-irc/issues/63

The bot still displays their 'global' name instead of the name they set for my server. And idea on how to get it to do this? Thanks!

**Comment by DarkSpyro003** [comment]
Hi @djyumene. As you've seen the issue #63 for this feature request is still open.
I made a fork in which this functionality is available on the branch server-nicknames https://github.com/DarkSpyro003/discord-irc/tree/server-nicknames
The pull request for it is open https://github.com/reactiflux/discord-irc/pull/107
You should try to avoid posting duplicate issues in the future.

**Comment by ekmartin** [comment]
Sorry about the delay @DarkSpyro003, I'll take a look at it as soon as possible.
