### ISSUE TITLE
trouble getting discord-irc set up

### ISSUE THREAD

**Issue by htsdeshi** [reactiflux/discord-irc#126]
following the instruction on this repo i ran into an error pretty quick 
i am running ubuntu 14.04 LTS

:~/discord$ npm install -g discord-irc

> discord-irc@2.0.1 prepublish /home/ubuntu/discord/discord-irc
> npm run build

\

> discord-irc@2.0.1 build /home/ubuntu/discord/discord-irc
> babel lib --out-dir dist

lib/bot.js -> dist/bot.js
lib/cli.js -> dist/cli.js
lib/errors.js -> dist/errors.js
lib/helpers.js -> dist/helpers.js
lib/index.js -> dist/index.js
lib/validators.js -> dist/validators.js
npm WARN engine discord-irc@2.0.1: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.47","npm":"2.15.1"})
npm ERR! tar.unpack untar error /home/ubuntu/.npm/discord-irc/2.0.1/package.tgz
npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "discord-irc"
npm ERR! node v0.10.47
npm ERR! npm  v2.15.1
npm ERR! path /usr/lib/node_modules/discord-irc
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/discord-irc'
npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/discord-irc']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/lib/node_modules/discord-irc',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/lib/node_modules/discord-irc',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/discord/npm-debug.log
ubuntu@ip-xxx-xx-xx-xxx:~/discord$

not running at root. I have nodejs version 0.10 that i got from the PPA i did not use apt-get.

**Comment by htsdeshi** [comment]
ok i had a legacy version of nodejs and upgraded to version 6 and i can get discord-irc to connect to the irc server and channels i specify but i do not see it in discord itself am I missing a step? I have the bot configured and token inside the config.json.

**Comment by htsdeshi** [comment]
alright for that last comment i had forgotten to invite the bot to the server which it has connected now. Is there some commands or will the test-config.js not work for this?

**Comment by ekmartin** [comment]
Hi @htsdeshi - sorry for the late answer. Have you managed to get the bot working yet? Not completely sure what you mean with your last sentence.

**Comment by DarkSpyro003** [comment]
Hello @htsdeshi 
Do you have any further news on this issue or may we close it?
