### ISSUE TITLE
use webhooks to mirror users usernames

### ISSUE THREAD

**Issue by macdja38** [reactiflux/discord-irc#128]
using webhooks it's possible for the bot to submit a username with each request, this could reduce the devide between discord and irc.

**Comment by ekmartin** [comment]
Hey @macdja38! This is definitely a cool idea. It's what [slack-irc](https://github.com/ekmartin/slack-irc/) does (albeit without webhooks), which is what this library is based on. It looks like discord.js is getting ready to ship webhook support, and when they have I think we should take a look at it. If you'd be interested in trying to implement it that would be awesome!

By the way, I know there's at least a few people that prefer how it is at the moment, where the bot always has the same username, and prefixes messages with the IRC usernames instead. I don't, and think it would be better to just add a suffix to the usernames instead, like `macdja38 (IRC)` - but it's worth keeping in mind.

**Comment by macdja38** [comment]
webhook support has been rolled out by discord. Webhooks still have the bot tag so I'm not sure how necessary adding the IRC tag to the user-names will be. I'll take a look at this if I have time but it won't be for the next little while.

**Comment by Fiaxhs** [comment]
Just saw you can provide an avatar with the message, not sure to do the matching however.

**Comment by macdja38** [comment]
@Fiaxhs I briefly looked over your PR and I don't think there is really any good option as far as avatars go... If none is specific when the webhook is executed it will use the one configured to it through the discord UI and I think that's probably the best option.

**Comment by Fiaxhs** [comment]
@macdja38 The only unpractical solution I see is to provide an array of base64 128x128 images somewhere in the config, so yeah...

**Comment by Fiaxhs** [comment]
@macdja38 Of course once I said there's no practical solution I implemented one.  However we need to wait for https://github.com/hydrabolt/discord.js/commit/c37cd3fd913773cfb53d784d12ddffad5fbc727f#diff-6b62447249975f23ee81d40061362573L573 to be released because currently `sendWebhookMessage` doesn't allow username override.
I'll hold the PR until then. (see https://github.com/Fiaxhs/discord-irc/commit/2f59cbe2ef183c11de25506307e0e45c10f7e90c )
