### ISSUE TITLE
Custom formatting between Discord and IRC

### ISSUE THREAD

**Issue by ProfX66** [reactiflux/discord-irc#13]
It would be really cool if I could customize the format that shows between the two services.

Like, I would like to strip the nick color that is sent to IRC, or have it show as [NICK] instead of <NICK>.

It would be really cool if it could just pull the rank color from Discord and use that instead of a random color.

**Comment by FastiJan** [comment]
I have similar issue, in quakenet channel mode +c prevents the usage of control codes(colors/bolds/etc). The bot cannot send to channel, because it forces the nick to have color. I tried using ircOptions stripColors, but it doesn't seem to work.

**Comment by FastiJan** [comment]
Got it somewhat working with no colors by just changing a line in
lib/bot.js Line ~147:

text = `<${coloredUsername}> ${text}`;
to
text = `<${username}> ${text}`;

then run build again.

unsure what else this might do or not do to work with channel flag +c.

**Comment by ekmartin** [comment]
@FastiJan, version 0.7.0 now includes an option that lets you disable irc colors by setting `ircNickColor` to false.
