### ISSUE TITLE
Mentioning by nickname

### ISSUE THREAD

**Issue by altyr** [reactiflux/discord-irc#137]
Thanks for making the bot display discord nicknames in IRC.
Currently _@_nickname doesn't work from IRC, are there plans to allow mentioning people by their nicknames? If not I could take a stab at this.

**Comment by ekmartin** [comment]
@DarkSpyro003 fixed this in https://github.com/reactiflux/discord-irc/pull/107 - but there were still a few issues to resolve so I urged her to open a new PR. If she doesn't have time I'm sure she wouldn't mind if you finished what she started, but should give it a little time first :)

**Comment by DarkSpyro003** [comment]
The basic functional code for it is in my fork (in branch server-nicknames DarkSpyro003/discord-irc:server-nicknames ) but it still needs some refactoring. There's probably a better way to write it than I did.
I don't have a lot of time for this and I generally don't write JavaScript.
If you want you can take a look at it.

**Comment by DarkSpyro003** [comment]
I've picked this issue up again and have made changes to make it work with the current API version.
I still have to fix the tests and do a thorough test and hope to have a pull request ready tomorrow.

WIP on develop branch https://github.com/DarkSpyro003/discord-irc/tree/server-nicknames-develop

**Comment by ekmartin** [comment]
Great @DarkSpyro003 - looking forward to the pull request!

**Comment by altyr** [comment]
Deployed @DarkSpyro003's version to test, looks good so far. Nice work.
I wonder if the regex used to match the name could be sensibly expanded to catch nicknames with spaces in them? On the other hand that might create a stack of other problems...

**Comment by DarkSpyro003** [comment]
I've thought about that as well @altyr but I think the only way to do that would have serious performance rammifications. You'd probably need a list of all the nicknames in the discord channel, and then search for occurences of @<nickname> of each of those to determine if someone was trying to mention them.
Not to mention, what would happen if someone was called <abc> and someone else <abc def> and someone wrote @abc def ?
Lets say it appears to be non-trivial and beyond the scope of this feature.

**Comment by ekmartin** [comment]
Published in version [2.1.4](https://github.com/reactiflux/discord-irc/blob/master/CHANGELOG.md#214---2016-11-14) - thanks again @DarkSpyro003.

**Comment by dumptruckman** [comment]
Do mentions coming from irc only work with the at sign? Traditionally, an IRC client will ping you if someone merely types your name. Is it suppose to work that way?

**Comment by altyr** [comment]
@dumptruckman As it is it only works with the at-sign. The bot uses it to detect words that might be usernames instead of trying to match every single word against an username.
