### ISSUE TITLE
Error after updating the relay on ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by dmodoomsirius** [reactiflux/discord-irc#142]
https://www.irccloud.com/pastebin/uhQxc5ZG/ this is the error after updating the relay
Here is the update log. https://www.irccloud.com/pastebin/NlSvPBWI/

**Comment by ekmartin** [comment]
Looks like you've got an old Node.js version! Try upgrading to version 6+, and it should be good. Upgrade instructions here: https://github.com/nodesource/distributions#installation-instructions

By the way, if you install with `npm install -g --no-optional discord-irc` you should be able to skip the native dependencies of discord.js (which discord-irc doesn't use).

**Comment by dmodoomsirius** [comment]
Thanks for the help :)

**Comment by ekmartin** [comment]
No problem. Let me know if it still doesn't work and I'll reopen :)
