### ISSUE TITLE
Issues getting discord-irc to work

### ISSUE THREAD

**Issue by Villazzz94** [reactiflux/discord-irc#145]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--config',
1 verbose cli   'C:\\Users\\Villazzz\\reactiflux\\discord-irc\\.git' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-irc@2.1.3~prestart: discord-irc@2.1.3
6 silly lifecycle discord-irc@2.1.3~prestart: no script for prestart, continuing
7 info lifecycle discord-irc@2.1.3~start: discord-irc@2.1.3
8 verbose lifecycle discord-irc@2.1.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-irc@2.1.3~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Villazzz\reactiflux\discord-irc\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\Users\Villazzz\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Users\Villazzz\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Villazzz\AppData\Local\Programs\Python\Python35\;C:\Program Files\nodejs\;C:\Users\Villazzz\AppData\Roaming\npm
10 verbose lifecycle discord-irc@2.1.3~start: CWD: C:\Users\Villazzz\reactiflux\discord-irc
11 silly lifecycle discord-irc@2.1.3~start: Args: [ '/d /s /c',
11 silly lifecycle   'node dist/index.js "--config" "C:\\Users\\Villazzz\\reactiflux\\discord-irc\\.git"' ]
12 silly lifecycle discord-irc@2.1.3~start: Returned: code: 1  signal: null
13 info lifecycle discord-irc@2.1.3~start: Failed to exec start script
14 verbose stack Error: discord-irc@2.1.3 start: `node dist/index.js "--config" "C:\Users\Villazzz\reactiflux\discord-irc\.git"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid discord-irc@2.1.3
16 verbose cwd C:\Users\Villazzz\reactiflux\discord-irc
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--config" "C:\\Users\\Villazzz\\reactiflux\\discord-irc\\.git"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error discord-irc@2.1.3 start: `node dist/index.js "--config" "C:\Users\Villazzz\reactiflux\discord-irc\.git"`
22 error Exit status 1
23 error Failed at the discord-irc@2.1.3 start script 'node dist/index.js "--config" "C:\Users\Villazzz\reactiflux\discord-irc\.git"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-irc package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node dist/index.js "--config" "C:\Users\Villazzz\reactiflux\discord-irc\.git"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-irc
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-irc
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ekmartin** [comment]
What node.js version do you have? discord-irc requires at least version 6.

**Comment by Villazzz94** [comment]
6.9.1

**Comment by Villazzz94** [comment]
2 info using npm@3.10.8
3 info using node@v6.9.1

**Comment by ekmartin** [comment]
So you're trying to run `npm start -- --config config.json` right? Could you try running `node dist/index.js --config config.json` directly?

**Comment by Villazzz94** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--config',
1 verbose cli   'config.json' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
4 verbose stack     at Error (native)
5 verbose cwd C:\WINDOWS\system32
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--config" "config.json"
8 error node v6.9.1
9 error npm  v3.10.8
10 error path C:\WINDOWS\system32\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
15 error enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

**Comment by ekmartin** [comment]
`no such file or directory, open 'C:\WINDOWS\system32\package.json'`? Either you're in the wrong directory or there's something weird with your node/npm install.

**Comment by Villazzz94** [comment]
Well this is odd there is no packgae.json in my system32

**Comment by Villazzz94** [comment]
hmm not having any luck finding my package.json

**Comment by Villazzz94** [comment]
what version should the init be?

**Comment by ekmartin** [comment]
Any reason you don't want to install the CLI and use that?
I.e. as the README explains:
```bash
$ npm install -g discord-irc
$ discord-irc --config config.json
```

**Comment by Villazzz94** [comment]
even when i do that 
discord-irc --config config-json doesnt work still.

still says no such file or directory

**Comment by Villazzz94** [comment]
$ discord-irc --config config.json
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Villazzz\config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at readJSONConfig (C:\Users\Villazzz\AppData\Roaming\npm\node_modules\discord-irc\dist\cli.js:43:35)
    at Object.run [as default] (C:\Users\Villazzz\AppData\Roaming\npm\node_modules\discord-irc\dist\cli.js:62:98)
    at Object.<anonymous> (C:\Users\Villazzz\AppData\Roaming\npm\node_modules\discord-irc\dist\index.js:23:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by ekmartin** [comment]
That means there's no config.json where you're trying to run it. You need to create a config file similar to the example in the README.

Here's a barebones example:
```json
[
  {
      "nickname": "BotNick",
      "server": "irc.freenode.net",
      "discordToken": "your-token-here",
      "channelMapping": {
         "#general": "#irc-channel"
      }
    }
]
```
