### ISSUE TITLE
problem with connecting to IRC znc bouncer

### ISSUE THREAD

**Issue by eerozeteen** [reactiflux/discord-irc#158]
Hi,
I have installed znc serwer on my raspberry pi. I want to connect my discord-irc bot to irc via my znc. I tring a lot of configs without any success. When i set bot to connect irc network directly bot work great, but i want connect it via znc. Here is my config file:

>[
 > {
  >  "nickname": "Bot",
   > "server": "10.10.1.5:9000",
  >  "discordToken": "token",
  >  "channelMapping": {
  >    "#discord": "#irc"
   >   },
  >    "ircOptions": {
  >  "userName": "login/network",
  >  "password": "pass"
 > }
>}
>]

I can connect (via xchat) to znc on 2 ways.
1. connect only to server (without any password), and type line as describe:

>* Looking up 10.10.1.5
>* Connecting to 10.10.1.5 (10.10.1.5) port 9000...
>* Connected. Now logging in...
>* Password required
>* *** You need to send your password. Try /quote PASS `<username>:<password>`
2. Configure xchat and type as server password: `<username>:<password>`

Can anyone help me with it?

**Comment by eerozeteen** [comment]
ok, i reconfigure znc to listening on default irc port 6667, and remove :9000 from server. And works.
So the question is how to use discord-irc on not default server port.

**Comment by DarkSpyro003** [comment]
Hello @eerozeteen 
You can pass the port via "port" in "ircOptions"
```
[
{
"nickname": "Bot",
"server": "10.10.1.5",
"discordToken": "token",
"channelMapping": {
"#discord": "#irc"
},
"ircOptions": {
"userName": "login/network",
"password": "pass",
"port:": 9000"
}
}
]
```
We use node-irc as the IRC client. See also https://node-irc.readthedocs.io/en/latest/API.html#client

**Comment by eerozeteen** [comment]
ok, thanks for replay, its works.
