### ISSUE TITLE
Issues after server restart

### ISSUE THREAD

**Issue by cauliflower69** [reactiflux/discord-irc#16]
We had it working perfect and since I restarted the server it connects works for a few seconds and then disconnects 

http://pastebin.com/f2vWS91v

Any help would be greatly appreciated

**Comment by ekmartin** [comment]
Hi! What Node.js and discord-irc versions are you running? The version number can be retrieved with `node --version` and `discord-irc --version`.

**Comment by cauliflower69** [comment]
Updated and the bridge is working, I'll report back if we have any other issues. Thanks for the reply

**Comment by ekmartin** [comment]
Glad you got it working! :smiley:
