### ISSUE TITLE
Some error.

### ISSUE THREAD

**Issue by jamesguessis** [reactiflux/discord-irc#162]
I mean I'm most likely doing this wrong, but I get this when I try running `discord-irc --config /home/jamesguessis/configs/dIRCord.json`
```discord-irc --config ~/config.json
/usr/local/lib/node_modules/discord-irc/dist/cli.js:48
      throw new _errors.ConfigurationError('The configuration file contains invalid JSON');
      ^

ConfigurationError: The configuration file contains invalid JSON
    at readJSONConfig (/usr/local/lib/node_modules/discord-irc/dist/cli.js:48:13)
    at Object.run [as default] (/usr/local/lib/node_modules/discord-irc/dist/cli.js:62:98)
    at Object.<anonymous> (/usr/local/lib/node_modules/discord-irc/dist/index.js:23:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)```

**Comment by ekmartin** [comment]
Hi! This is because discord-irc requires at least Node.js version 6 and upwards, since that's the minimum supported version of the library we use for Discord related work ([discord.js](https://github.com/hydrabolt/discord.js)).

**Comment by ekmartin** [comment]
Wop, apparently you edited the original post (which had another error).
The new error you added is because your JSON config is badly formatted. Maybe you have a trailing comma or similar? If you remove comments you can use something like http://jsonlint.com/ to validate it (or paste it here without secrets and I can take a look).

**Comment by jamesguessis** [comment]
Yeah I figured that it needed to be updated seconds after I posted the issue

And yeah apparently I had a backslash at the end of the json for some reason, probably a typo. Thanks keyboard ;P

I'm using this
```  {
    "nickname": "DiscordBot",
    "server": "10.0.0.22",
    "discordToken": "hi": {
      "#general": "#general",
      "#music": "#music",
      "#osu": "#osu",
      "#mania": "#mania",
      "#memes": "#memes",
      "#bot": "#bot",
      "#chosen": "#chosen",
      "#twitch": "#twitch",
      "#twitch-notifications": "#twitch-notifications",
      "#spam": "spam"
     }
   }
```
should that work?

**Comment by ekmartin** [comment]
No, you need to put the channels bellow a `channelMapping` property - look at the example in the README.

**Comment by jamesguessis** [comment]
Thank you, now it's working 👍

**Comment by n0rt0x** [comment]
Trying to get the bridging to work on Raspbian but so far no luck. This is what I get: usr/lib/node_modules/discord-irc/node_modules/check-env/index.js:12
      throw new Error('Missing environment variable ' + missing[0]);
      ^

Error: Missing environment variable CONFIG_FILE
    at module.exports (/usr/lib/node_modules/discord-irc/node_modules/check-env/index.js:12:13)
    at Object.run [as default] (/usr/lib/node_modules/discord-irc/dist/cli.js:59:59)
    at Object.<anonymous> (/usr/lib/node_modules/discord-irc/dist/index.js:12:27)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

I've no clue what it means, is it something silly i overlooked or more complex?

**Comment by n0rt0x** [comment]
Also got these when running: sudo npm install -g discord-irc

npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
/usr/bin/discord-irc -> /usr/lib/node_modules/discord-irc/dist/index.js
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.

@ekmartin could you help me out on this one?
