### ISSUE TITLE
Setup with Slack?

### ISSUE THREAD

**Issue by Faskis** [reactiflux/discord-irc#163]
I've been trying to see if this is possible to setup with Slack's IRC gateway. Our community is looking at transitioning from Slack to Discord, but one of the things I'd like to carry over is our in-game integration with one of these services. My intention to make it simple was to utilize Slack as a tunnel between the game server and Discord (Slack is currently connected to the game server). I've tried including the generated password for the bot account in the server address but it doesn't appear to be connecting properly. If I remove the password, I get the following error:

`error: Received error event from IRC command=err_nologin, rawCommand=444, commandType=error, args=[<NICKNAME>, Invalid user name or password]`

Any ideas or other potential solutions to setup what I'm trying to accomplish would be greatly appreciated.

**Comment by DarkSpyro003** [comment]
Hello @Faskis,

The error seems to indicate you're not logging in to the Slack gateway correctly.
You probably want the following flags set in ircOptions:
"secure": true,
"userName": "gatewayusername",
"password": "gatewaypassword"
I'm not familiar with how the Slack gateway handles logins. You might also need to set:
"sasl": true

See also:
http://node-irc.readthedocs.io/en/latest/API.html
https://my.slack.com/account/gateways

Please let me know if you were successful or not in your setup attempt.

**Comment by Faskis** [comment]
It doesn't throw the error with that setup so I assume it's connected, but messages aren't being sent to the Slack server. Debugging only shows this when a message is sent on Discord:

`debug: Channel Mapping #admin #admin`

**Comment by Faskis** [comment]
I didn't realize there was a debug option for the IRC connection itself, so that's making this a bit easier to sort out, but now I'm getting this error during the IRC connection:

`TypeError: Cannot read property 'trim' of undefined
    at Client.<anonymous> (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:372:44)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at iterator (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at Socket.handleData (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)`


If I specify a secure connection, I get this:

`TypeError: Cannot read property 'trim' of undefined
    at Client.<anonymous> (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:372:44)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at iterator (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at TLSSocket.handleData (/usr/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)`

**Comment by ekmartin** [comment]
Without having looked too much at it, it might be that Slack's IRC gateway doesn't implement the protocol in a way node-irc expects.

On the other hand, if you _really_ wanted to what you could do would be to setup [slack-irc](https://github.com/ekmartin/slack-irc) (which discord-irc is based on), and have that act as a bridge between Slack and IRC first.

**Comment by Faskis** [comment]
It's looking like it's erroring out on listing the clients within the channel. The issue with the slack-irc setup is that it would require me to setup a separate IRC server, no? I was kind of wanting to avoid that (hence why I'm trying to use Slack as the server) as setting them up tends to be a PITA.

**Comment by ekmartin** [comment]
Yeah, or just use a public one with private channels.
If you had the time you could fork slack-irc and rip out the Discord code from discord-irc, basically creating a discord-slack bridge. I.e. gluing the Discord parts from this project with the Slack parts from slack-irc.

**Comment by ekmartin** [comment]
Closing this as out of scope, let me know if you have any more questions.

**Comment by BeauBouchard** [comment]
I also have tried this and it 💯 works

If you do this fix listed here https://github.com/martynsmith/node-irc/pull/496/files
for the ./node_modules/irc/lib/irc.js at line 414, 

It will successfully join a slack by connecting to an IRC gateway. You need to configure your slack to use a gateway at http://youslackgroup.slack.com/admin/settings#gateways. 

![https://i.imgur.com/OoT6rVQ.png](https://i.imgur.com/OoT6rVQ.png)

Here is what the configuration file looks like for the Discord Slack bridge. 

```
[
  // Bot 1 (minimal configuration):
  {
    "nickname": "BOTNAME",
    "server": "waheverslacknamehere.irc.slack.com",
    "discordToken": "discord token here",
    "channelMapping": {
      "#general": "#general"
    },
    "ircOptions": {
      "password": "password from slack here",
      "port": 6697,
      "secure": true
    }
  }
]
```

Big thanks to @ekmartin and other contributors, this is the best bridge for slack <-> discord out there.
