### ISSUE TITLE
IRC Options config

### ISSUE THREAD

**Issue by hydraik** [reactiflux/discord-irc#165]
Is it possible in the IRC options config to make it so that everytime someone logs on or off of IRC that message is sent to discord via the bot? I could care less about irc knowing discords status but it'd be nice to know who's in the IRC channel, also is there a way to enable a command that would spit out the list of all users on IRC into the discord chat? could you give me an example of that config?

Thanks in advance and this is a really great Bot! Thanks!

**Comment by DarkSpyro003** [comment]
This has also been suggested in #92
