### ISSUE TITLE
Getting "cannotsendtochan" error when sending messages to irc.

### ISSUE THREAD

**Issue by arandomperson23** [reactiflux/discord-irc#170]
I have a bot connecting two irc servers to two discord channels. Messages to Discord are being received properly but I get `error: Received error event from IRC prefix=server.org, server=server.org, command=err_cannotsendtochan, rawCommand=404, commandType=error, args=[Botname_Discord, #channel, Cannot send to channel]
` when sending to irc.
I'm assuming it's something wrong with my config. Does this look right?

```
[
  // Bot 1:
  {
    "nickname": "Botname_Discord",
    "server": "irc.freenode.net",
    "discordToken": "TOKEN",
    "channelMapping": {
      "#channel1": "#channel1"
    }
  },
  // Bot 2:
  {
    "nickname": "Botname_Discord",
    "server": "irc.quakenet.org",
    "discordToken": "TOKEN",
    "channelMapping": {
      "#channel2": "#channel2"
    }
  }
]
```
Uh, sorry if I mess something up here, I've never submitted an issue before.

**Comment by DarkSpyro003** [comment]
Is there any chance the bot in IRC does not have the prerequisite rights? (i.e. not +v in a channel which is +m) or otherwise equivalently lacking in permissions?

**Comment by arandomperson23** [comment]
No, I was using a public channel (#leagueoflegends on quakenet). I have no problems sending messages through a normal client.

**Comment by devzspy** [comment]
We have +c channel mode (deny colors) enabled 

-FalconSpy - Channel admin on #leagueoflegends of QuakeNet

**Comment by devzspy** [comment]
@arandomperson23 We have +c channel mode (deny colors) enabled

-FalconSpy - Channel admin on #leagueoflegends of QuakeNet

**Comment by arandomperson23** [comment]
Oh, yes I see it now. I'll be honest, the last time I used this channel was late 2015 and messages worked then. This is what I get for not checking. 

Sorry for wasting everyone's time, I guess this can be closed.

**Comment by ekmartin** [comment]
@arandomperson23 you can also set `ircNickColor` to `false`, which would prevent the bot from posting to IRC with colors.
