### ISSUE TITLE
Implement CTCP signals

### ISSUE THREAD

**Issue by polyzium** [reactiflux/discord-irc#178]
Make the bot respond to CTCP signals as well as make it send them using some sort of `!ctcp` command on Discord side

**Comment by Throne3d** [comment]
CTCP signals like this? https://en.wikipedia.org/wiki/Client-to-client_protocol#Common_CTCP_Commands

I would expect sending them to be out of scope at present, as the bot doesn't currently (to my knowledge) accept any commands. Responding to CTCP signals seems fair to ensure it acts like a proper IRC client, though.

**Comment by stargatecmd2009** [comment]
Some IRCd's require CTCP version to be sent on connect.
https://github.com/inspircd/inspircd-extras/blob/master/2.0/m_requirectcp.cpp

**Comment by Throne3d** [comment]
Closing in favor of #385, which is more specific. (PRs appreciated!)
