### ISSUE TITLE
Restrict usage of commands to Discord roles

### ISSUE THREAD

**Issue by OfotViking** [reactiflux/discord-irc#180]
It would be useful (at least on non-public irc servers) to have an option to restrict the usage of irc bot commands to Discord roles.

Config settings may look something like this: 
```
"commandCharacters": ["!", "."],
"IRCcommandToDiscordRoleMappings": {
	"!command1" : "@admins",
	".command2" : "@group",
	"!command3" : "@everyone"
},```

**Comment by ekmartin** [comment]
I'm slightly confused how this would work, do you mean that !command1 would only be forwarded to the IRC channel as a command if the user issuing it was an admin? Couldn't the user just join the IRC channel and write the command there? Or do you have a scenario where the Discord server is public, while the IRC channel is private?

Regardless, I think this is a bit out of scope for discord-irc, even though I understand that it could be useful. Sorry about that, but feel free to implement in a fork if you're interested and have the time!
