### ISSUE TITLE
Setup issue - this.ircClient.send(...element);

### ISSUE THREAD

**Issue by jrogers512** [reactiflux/discord-irc#182]
> $ discord-irc --config ~/discord-irc/config.json
> /usr/local/lib/node_modules/discord-irc/dist/bot.js:95
>         this.ircClient.send(...element);
>                             ^^^
> 
> SyntaxError: Unexpected token ...
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/discord-irc/dist/helpers.js:12:12)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)

Any ideas what might be causing this issue?  I followed the README for installation, using the npm -g install method.

**Comment by ekmartin** [comment]
Upgrade your Node version to 6 or newer :)
