### ISSUE TITLE
Errors using 'npm install'

### ISSUE THREAD

**Issue by TemperedChrome** [reactiflux/discord-irc#184]
Hello, every time I try to run npm install on the terminal after cloning the repo, I get an error, I have tried on multiple machines running different versions of Linux to no avail

The issue is as follows:
http://pastebin.com/raw/dGrLvDnf

**Comment by ekmartin** [comment]
Upgrade your Node.js version, discord.js needs at least version 6 :)

**Comment by TemperedChrome** [comment]
d'oh! I though I did update it and never even looked at my error long enough to realize that I was using the wrong version, thanks man, turns out that node is a lot weirder to update than I thought. Maybe I should update my distro soon as the packages on here are getting super old

**Comment by ekmartin** [comment]
No worries - glad you got it working.
