### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by Wyattmin8or246** [reactiflux/discord-irc#185]
So I've been trying to create a bot that can send messages for me once every 5 minutes, but every time I try to run the bot, it gives me this:

SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by ekmartin** [comment]
Try upgrading your Node.js version, discord.js requires at least Node.js version 6.

**Comment by Wyattmin8or246** [comment]
I have the latest version, 7.4.0 installed. Could it be something to do with my coding?

var discord = require("discord.io");
var bot = new Discord.bot();
    autorun: true,
    email: "my email", // email
    password: "my password", // password
  //OR
    token: "Mjc0MDU5NjAwOTc2Njc0ODE2.C2xEow.Q8hYJS7jRkAY6_IRz0UzxMGUxVg"
});

bot.on('ready', function() {
    console.log(Text Bot + " - (" + #0980 + ")");
});

bot.on('message', function(user, userID, channelID, message, rawEvent) {
    if (message === "!test") { // command to trigger
      var interval = setInterval (function (){
        bot.sendMessage({
          to: channelID,
          message: "Hi" // message to send
        });
      }, 1000); // time between each interval in milliseconds
    }
    // New command starts here
    else if (message === "!help") {
      bot.sendMessage({
        to: channelID,
        message: "Insert Message here"
      });
    }
    // Ends here
});

**Comment by polyzium** [comment]
Congrats. You just exposed your token...

**Comment by ekmartin** [comment]
Yes, you have a syntax error on line 3. I'm not sure why you're posting the issue in this repository though, it looks like you're using discord.io and not discord-irc?

https://github.com/izy521/discord.io/issues

Regardless, it should be:
```js
var bot = new Discord.Client({
  autorun: true,
  // and so on
});
```
