### ISSUE TITLE
Role mensions display as number on irc

### ISSUE THREAD

**Issue by PieterHollevoet** [reactiflux/discord-irc#186]
When you @ mention a role on discord, It displays on IRC as numbers. 
For example
discord : @sysadmin  ==> irc : @&233558485999...

Could you give me some pointers to where the problem lies and we will fix it ourselves.

**Comment by ekmartin** [comment]
`parseText` is responsible for translating user and channel highlights to a readable format.
Something like the one for channels should do the trick: https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L140-L143

Pull request welcome!

**Comment by Throne3d** [comment]
Fixed in #203.
