### ISSUE TITLE
Pm2 issue

### ISSUE THREAD

**Issue by TheBaconSpace** [reactiflux/discord-irc#188]
@ekmartin 
![Discord-irc-pm2](https://surl.im/i/y9caq.png)

**Comment by ekmartin** [comment]
You can pass arguments through pm2 by adding a double dash first, i.e. `-- --config config.json`. I don't think `node discord-irc` will work though, maybe just `pm2 start discord-irc` or `pm2 start dist/index.js` after following the build instructions here: https://github.com/reactiflux/discord-irc#installation-and-usage

**Comment by Kovaelin** [comment]
Just in case anyone in the future is looking for answers, `pm2 start discord-irc -- --config config.json` worked just fine.

**Comment by s4turns** [comment]
I am having the same issue, I used the command above (pm2 start discord-irc -- --config config.json) and I get the follow error:

21|discord | { Error: Cannot find module '/root/discord-irc/discord-irc'
21|discord |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
21|discord |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
21|discord |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
21|discord |     at Module._compile (internal/modules/cjs/loader.js:778:30)
21|discord |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
21|discord |     at Module.load (internal/modules/cjs/loader.js:653:32)
21|discord |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
21|discord |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
21|discord |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
21|discord |     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
