### ISSUE TITLE
Strip mIRC formatting characters

### ISSUE THREAD

**Issue by Sanqui** [reactiflux/discord-irc#195]
Messages from the IRC side with colors show up as numbers on the Discord side.

Could probably just use this: https://www.npmjs.com/package/irc-colors

**Comment by ekmartin** [comment]
Yep! https://github.com/reactiflux/discord-irc/pull/166 fixed this, but the author wasn't interested in adding irc-colors for it - which I think is a better solution. Feel free to send a PR if you have time!
