### ISSUE TITLE
Messages to IRC contain &zwj; in nicknames; Causes issues with some clients (and platforms)

### ISSUE THREAD

**Issue by duckspike** [reactiflux/discord-irc#196]
As the title states, when the bot sends messages from Discord to IRC, the formatted username of the Discord chatter contains &zwj; between each letter of the nickname. An example is pictured below.

![screen shot 2017-03-10 at 9 50 56 pm](https://cloud.githubusercontent.com/assets/15951552/23836915/8c1eb3bc-075e-11e7-9400-d149bc90cf8f.png)

It seems to cause issues with push notifications on Google Chrome on Mac OS as well IRC applications on iOS devices. On iOS, the character does not render properly and causes the application to slow down for a length of about 0.3 seconds. A below screenshot proves the issue with the Mutter IRC client for iOS. 

![img_1121](https://cloud.githubusercontent.com/assets/15951552/23836975/6878fcfa-075f-11e7-9d25-a2928cc31368.PNG)

Using the latest version of discord-irc as of 3/10/17 and nodejs 6.10.0 compiled from source.

**Comment by ekmartin** [comment]
That's unfortunate. I've reverted the changes introduced in #193 and 2.2.0, and published a new version (2.2.1). @Sanqui do you have any suggestions for how we might fix this?
