### ISSUE TITLE
Avoid self-message highlighting on IRC

### ISSUE THREAD

**Issue by ekmartin** [reactiflux/discord-irc#197]
#193 originally fixed this, but caused issues with some clients (#196). Open for other suggestions.

**Comment by Sanqui** [comment]
Sadly, I don't think there's a catch-all solution.  With a plethora of systems and IRC clients, you're always going to run into issues with some of them.  I would go with @Kroisse's #194 implementation which lets maintainers turn the feature on or off depending on if it works for their particular users.

**Comment by Sanqui** [comment]
Putting the zero width character between the first and second letter only, rather than each of them, like #194 did, should help reduce the collateral damage when the character is visible, at slight risk of triggering more highlights (e.g. for people who have a prefixed `_name`).
