### ISSUE TITLE
Discord prints Unicode nickname to undefined

### ISSUE THREAD

**Issue by ZerglingGo** [reactiflux/discord-irc#200]
When IRC sends a chat as a Korean nickname, discord-irc prints nickname to undefined.

- IRC
![hexchat_2017-03-19_16-55-09](https://cloud.githubusercontent.com/assets/3365053/24079151/d8563b7c-0cc4-11e7-992c-8edff8c80fba.png)
![hexchat_2017-03-19_16-56-59](https://cloud.githubusercontent.com/assets/3365053/24079167/208bf850-0cc5-11e7-94e0-eb9ea6db72ed.png)
- Discord
![discord_2017-03-19_16-55-18](https://cloud.githubusercontent.com/assets/3365053/24079152/dad8a222-0cc4-11e7-9fe0-10b45f4a0950.png)
![discord_2017-03-19_16-56-52](https://cloud.githubusercontent.com/assets/3365053/24079166/1e17ae5c-0cc5-11e7-8f65-d2241796a7e0.png)

**Comment by Throne3d** [comment]
I don't actually know of any IRC servers that support Unicode nicknames – do you know of a public one I could test this on? (Not an author of the bot but I'd be willing to try to find the issue and submit a PR.)

**Comment by ZerglingGo** [comment]
irc.luatic.net:7778 - This is Korean UTF-8 IRC Server

**Comment by Throne3d** [comment]
Thanks!

Unfortunately it looks like there's a problem with this in node-irc, and [there has been an open issue for a year about it](https://github.com/martynsmith/node-irc/issues/456). I'm not really sure what to do about that. I'll have a look into fixing it, but I'm not sure they're responding to pull requests very quickly, unfortunately.
