### ISSUE TITLE
As of today, unable to get bot into my discord server

### ISSUE THREAD

**Issue by BlinkTetris** [reactiflux/discord-irc#209]
Does this config look correct?  
  {
    "nickname": "DiscordRelay",
    "server": "irc.freenode.net",
    "discordToken": "wmjjNVUu82XWhkdBssMso3BwM5spOw89",
    "autoSendCommands": [ // Commands that will be sent on connect
      ["PRIVMSG", "NickServ", "IDENTIFY XXXXXXX XXXXXXXX"]
    ],
    "channelMapping": {
      "#achievements": "#harddrop"
    }
  }
]

I noticed other people's tokens have underscores and decimals and are longer than mine, so I'm wondering if I'm grabbing it from the correct place.

Anyways, I reach up to:
[root@harddrop fixtures]# discord-irc --config /home/harddrop.com/discord/discord-irc/test/fixtures/test-config.json
info: Connected to IRC

Any messages from IRC will not relay since the bot is not in the channel.  I've already done this:
https://discordapp.com/oauth2/authorize?client_id=XXXXXXXX&scope=bot&permissions=0
successfully but the bot still does not show up.

**Comment by rahatarmanahmed** [comment]
If that's your real discord token I suggest revoking it and getting a new one. you shouldn't post that in public.

**Comment by BlinkTetris** [comment]
Thanks, it's not.  I modified it.

**Comment by rahatarmanahmed** [comment]
By "as of today" do you mean that this config was working before?

**Comment by BlinkTetris** [comment]
Okay let me explain some more.  I have a config that was working fine for over a year.  I then received this e-mail yesterday:  

It appears your bot, object at 0x7f48aaa8b490, has connected to Discord more than 1000 times within a short time period. Since this kind of behavior is usually a result of a bug we have gone ahead and reset your bot's token.

Grabbed my new bot token today, did a pull of the latest discord-irc code and that's where i'm at now.  The bot can connect to IRC and seems to work fine, it just isn't connected to discord to relay the messages.

**Comment by BlinkTetris** [comment]
info: Connected to IRC
info: Tried to send a message to a channel the bot isn't in: 

The other thing is, even when I put in a fake discord token the bot still gets to the same state (connects to IRC and fails to relay message to discord).  I'm wondering if the token is incorrect, but it seems correct because i'm grabbing it from the "Client Secret Reveal".

**Comment by BlinkTetris** [comment]
Found my problem.  Closing this.

I used my Client Secret instead of my App Bot User Token.
