### ISSUE TITLE
Discord Channel key

### ISSUE THREAD

**Issue by devildog4355** [reactiflux/discord-irc#212]
Trying to add using Discord channel key to prevent it from connecting to other similar named channels on other servers. is this possible?

**Comment by Throne3d** [comment]
When you say channel key, do you mean the numeric ID? If so, support was added for that in 8c37393ca68f8022037d1f5b24addf7b36f646e0, which hasn't yet been published in a release version.

**Comment by devildog4355** [comment]
yes, this is what i was referring to. Thank you.
