### ISSUE TITLE
commandCharacters only works one way.

### ISSUE THREAD

**Issue by Gerppuli** [reactiflux/discord-irc#217]
So, what I'm trying to use the bot for is forwarding the songrequests from Twitch chat to my Discord MusicBot. The problem is that it only detects the message as a command when posting from Discord to Twitch, not the other way around. Example: http://imgur.com/a/6uRVr

**Comment by Throne3d** [comment]
Is there any need to have the command characters differ (so e.g. only `!` counts as a command character for IRC, but both `!` and `@` count for Discord), or would it work fine to use the same `commandCharacters` list both ways?

**Comment by Throne3d** [comment]
(The PR referencing this assumes there's no need for the command characters to differ.)
