### ISSUE TITLE
Sync channel topic

### ISSUE THREAD

**Issue by williamjacksn** [reactiflux/discord-irc#220]
It would be nice if the topic in the IRC channel got sent to Discord.

**Comment by Throne3d** [comment]
This should be doable. I'm not sure whether to make it configurable or have it happen by default. It could be nice to also mirror the Discord topic back to IRC.

The library we use for the IRC side of the bot appears to send the 'topic' event when the bot joins a channel, as well as when a topic is changed, so this may be a potential problem in the implementation. Perhaps we could use a debounce when the bot joins a channel, so it won't mirror any topic events it receives for a second? (This may not work depending on the order of the events, and could be subject to weird behavior on bad connections. If the `topic` event is instead sent before `join`, we could discard the event as we are not yet in the channel.)

> 'topic'
> `function (channel, topic, nick, message) { }`
> Emitted when the server sends the channel topic on joining a channel, or when a user changes the topic on a channel. See the raw event for details on the message object.

-[API](https://node-irc.readthedocs.io/en/latest/API.html#'topic')

For the Discord → IRC route: this would probably be done using a hook on the `channelUpdate` [event](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=channelUpdate) that checks the old and new channels for a difference in topic; it would need to make sure it handles [VoiceChannel](https://discord.js.org/#/docs/main/stable/class/VoiceChannel)s being updated, too, as they don't, I think, have topics.

**Comment by ekmartin** [comment]
There's no doubt that this is doable, but is it truly necessary?
If a lot of people find it useful I'd be open to adding it behind a configuration option, but with an already quite bloated set of options it would be good to have a solid need for it first.

**Comment by williamjacksn** [comment]
I don't really require this feature anymore, so I am going to close this issue. Feel free to re-open if you want.
