### ISSUE TITLE
Global Password

### ISSUE THREAD

**Issue by Nobabs27** [reactiflux/discord-irc#223]
How do I connect to a server that has a global password with the bot?
I tried the "AUTH" option but that doesn't change anything...

**Comment by Nobabs27** [comment]
To be specific:

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Incorrect login details were provided.`

**Comment by ekmartin** [comment]
Try passing `password` through `ircOptions`:
```json
"ircOptions": {
  "password": "pw"
}
```

and username if you need that - also, if the server uses SASL you can enable that with `"sasl": true`, under `ircOptions`.

**Comment by Nobabs27** [comment]
Thanks!  It logs in.
Still getting the error though, maybe it was not related.
Now I just need to fully set it up...

**Comment by ekmartin** [comment]
Hm, that's weird. Did you remove your `AUTH` option?

**Comment by Nobabs27** [comment]
yes
