### ISSUE TITLE
Different colors for different irc nicks

### ISSUE THREAD

**Issue by dmodoomsirius** [reactiflux/discord-irc#224]
Hello

Can you give each user who types a different color? would be easier for readability.

Thanks

**Comment by ekmartin** [comment]
Are you talking about coloring the whole IRC message? Different nicks are already given different colors. If coloring the whole message is what you're talking about I think I originally decided against that because it resulted in a less readable and more intrusive result in the end.

**Comment by dmodoomsirius** [comment]
I was talking about the nick name on the discord side. I will try to update then.

**Comment by ekmartin** [comment]
I don't think Discord supports colors in messages?

**Comment by dmodoomsirius** [comment]
that I am not sure. I will attempt to look into as well.

**Comment by dmodoomsirius** [comment]
Looking at https://discordapp.com/developers/docs/resources/channel messages support color apparently.
Between Timestamp and footer.

**Comment by ekmartin** [comment]
That's for embed objects.

**Comment by Throne3d** [comment]
This seems not doable at present, then, since I don't think using embed objects for each message would be a very useful step to take here? If people care about it sufficiently then we can probably reopen this at a later stage.

**Comment by Kovaelin** [comment]
`"ircNickColor": false, // Gives usernames a color in IRC for better readability (on by default)`

Does this mean that the default (on) is false? Would someone please provide a screenshot for what coloured nicknames look like? Is it the name of the bot that changes or the nicknames themselves? I can't seem to see any differences in HexChat or AndChat. Thanks.
