### ISSUE TITLE
Failing tests on debian wheezy

### ISSUE THREAD

**Issue by mtfurlan** [reactiflux/discord-irc#23]
I'm attempting to run this on Debain Wheezy amd64.
I cloned the repo, ran `npm install`, `npm run build`.
It fails optional dependencies `fsevents@1.0.6`, `node-icu-charset-detector@0.1.4`
I then run `npm test`, outputs http://sprunge.us/cfRM
Suggests I include npm-debug.log: http://sprunge.us/MbXE
`npm ls`: http://sprunge.us/VdWM

I do have node installed locally, but I don't think that can matter in this case?

Many thanks for any help.

**Comment by ekmartin** [comment]
Weird. What version of node do you have?

**Comment by mtfurlan** [comment]
`node --version` returns `v0.10.40`

**Comment by ekmartin** [comment]
That's quite old, could you try [upgrading](https://github.com/nodesource/distributions#installation-instructions) to a later version?

**Comment by mtfurlan** [comment]
Ah, hm. Discord-irc complained about version for a while, but then stopped and it seems I didn't do anything, just forgot it was an issue.
I'll work on upgrading this evening.

**Comment by mtfurlan** [comment]
Yeah, that was totally it. Sorry for the bother.

**Comment by ekmartin** [comment]
No problem, glad it worked out.
