### ISSUE TITLE
Word filter

### ISSUE THREAD

**Issue by dgibbs64** [reactiflux/discord-irc#231]
Im not sure if this is possible or in scope of this project however it would be great to have a filter that would allow discord-irc to only post when it see's specific words. I am using this project to post from the steamdb.info real time updates irc channel #steamdb-announce to the LinuxGSM discord server. 

While is is interesting to see the massive amount of changes posted to steam I mainly only really interested in "dedicated server" updates. As this will alert server admins a server update is now available. Thank you

**Comment by ekmartin** [comment]
This would be a bit too out of scope ye. It shouldn't be too hard to implement in a fork if you're interested though. You could for example add a 

```js
if (!text.includes('important message')) return;
```

to the start of https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L312

**Comment by dgibbs64** [comment]
@ekmartin thanks for the fast reply. I may just have to do that :). I will have a play around with that and see what I can do.

**Comment by ekmartin** [comment]
No worries - let me know if you get stuck and I'll be happy to give advice.
