### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by rnyberg** [reactiflux/discord-irc#232]
```
npm WARN discord.js@11.0.0 requires a peer of erlpack@hammerandchisel/erlpack#master but none was installed.
npm WARN discord.js@11.0.0 requires a peer of node-opus@^0.2.0 but none was installed.
npm WARN discord.js@11.0.0 requires a peer of opusscript@^0.0.1 but none was installed.
npm WARN discord.js@11.0.0 requires a peer of uws@^0.12.0 but none was installed.
```

I tested this: `npm install -g erlpack@hammerandchisel/erlpack#master` but attempting to npm install the cloned repo still throws the same error. Maybe the instructions could be a bit more clear as I couldn't find anything helpful even after googling for a good bit.

**Comment by ekmartin** [comment]
Those are optional dependencies of discord.js - so should work completely fine without. We might want to add `hammerandchisel/erlpack` though, apparently it makes websocket serialization/deserialization faster:

> erlpack for significantly faster WebSocket data (de)serialisation (npm install hammerandchisel/erlpack --save)

**Comment by rnyberg** [comment]
Feel dumb now, didn't try continuing with the installation as big red "UNMET PEER DEPENDENCY" felt like a fatal error. :)

**Comment by ekmartin** [comment]
We should probably add a note to the README about that!

**Comment by Kovaelin** [comment]
Would that particular dependency now be `discordapp/erlpack`?
