### ISSUE TITLE
Vhost?

### ISSUE THREAD

**Issue by Jahner** [reactiflux/discord-irc#233]
["VHOST", "Login Pass"],

Added this to my script. Everything still works but it doesn't set the vhost.

It worked on a previous install

**Comment by Jahner** [comment]
Probably be better if I included the whole config.

{
    "nickname": "AirlockRelay",
    "server": "irc.theairlock.net",
    "discordToken": "token_is_here",
    "autoSendCommands": [ // Commands that will be sent on connect
        ["PRIVMSG", "Nickserv", "ghost AirlockRelay password"],
        ["NICK", "AirlockRelay"],
        ["VHOST", "eve-radio password"],
        ["PRIVMSG", "NickServ", "IDENTIFY password"]
 ] ,
    "channelMapping": { // Maps each Discord-channel to an IRC-channel, used to direct messages to the correct place
      "#theairlock": "#theairlock",
        "#irchelp": "#irchelp" // Add channel keys after the channel name
    },
    "ircOptions": { // Optional node-irc options
      "floodProtection": true, // On by default
      "floodProtectionDelay": 500, // 500 by default
          "autoRejoin": true,
          "retryCount": 10
    },
    "ircNickColor": false, // Gives usernames a color in IRC for better readability (on by default)
    // Makes the bot hide the username prefix for messages that start
    // with one of these characters (commands):
    "commandCharacters": ["!"]
  }
  ]

**Comment by Jahner** [comment]
Config that worked on another server

[
{
"nickname": "Nick",
"server": "irc.theairlock.net",
"discordToken": "Token",
"channelMapping": {
"#general": "#eve-radio",
"#eve-radio-ingame": "#eve-radio-ingame",
"#er-staff": "#er-staff"
},
"autoSendCommands": [
["VHOST", "login password"],
["PRIVMSG", "NickServ", "GHOST Nick Password"],
["NICK", "Nick Password"],
["PRIVMSG", "NickServ", "IDENTIFY Password"]
],
"ircNickColor": false,
"commandCharacters": ["!", "."]
}
]

Receiving error

ConfigurationError: The configuration file contains invalid JSON
    at readJSONConfig (/usr/local/lib/node_modules/discord-irc/dist/cli.js:48:13)
    at Object.run [as default] (/usr/local/lib/node_modules/discord-irc/dist/cli.js:62:98)
    at Object.<anonymous> (/usr/local/lib/node_modules/discord-irc/dist/index.js:23:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)

**Comment by Throne3d** [comment]
Are you missing the start square bracket from your configuration or did you just forget to copy that? (The error looks like your JSON has a syntax error, and unmatched parentheses could cause that.)

**Comment by Jahner** [comment]
It just didn't copy it over. This is the current config that works with no errors. Vhost doesn't get applied.


 [
 {
    "nickname": "Nick",
    "server": "irc.theairlock.net",
    "discordToken": "Token",
    "autoSendCommands": [ // Commands that will be sent on connect
                ["PRIVMSG", "NickServ", "GHOST Nick Password"],
                ["NICK", "Nick"],
                ["VHOST", "Login Password"],
                ["PRIVMSG", "NickServ", "IDENTIFY Password"]
],
    "channelMapping": { // Maps each Discord-channel to an IRC-channel, used to direct messages to the correct place
                "#general": "#eve-radio",
                "#eve-radio-ingame": "#eve-radio-ingame",
                "#er-staff": "#er-staff" // Add channel keys after the channel name
    },
    "ircOptions": { // Optional node-irc options
      "floodProtection": true, // On by default
      "floodProtectionDelay": 500, // 500 by default
          "autoRejoin": true,
          "retryCount": 10
    },
    "ircNickColor": false, // Gives usernames a color in IRC for better readability (on by default)
    // Makes the bot hide the username prefix for messages that start
    // with one of these characters (commands):
    "commandCharacters": ["!"]
  }
  ]

**Comment by Throne3d** [comment]
Do you get any output in console? Especially errors. (Make sure to redact any passwords / tokens.)

**Comment by Jahner** [comment]
No errors. All that displays in the norm:

info: Connected to Discord
info: Connected to IRC

**Comment by ekmartin** [comment]
Ye, is `VHOST` a valid IRC command on the network? `autoSendCommands` are for actual IRC protocol messages, not the same as doing e.g. `/msg` in an IRC client. How would you do it with a client?

**Comment by Jahner** [comment]
vhost is a valid command on the network. With a client you do /vhost Login Pass

**Comment by Throne3d** [comment]
Hm. Could you enable debug in the config? That is, add to the `"ircOptions": { … }` bit `"debug": true`? (Make sure to redact any passwords / tokens from the logs.)

**Comment by ekmartin** [comment]
Because you can do `/vhost login pass` doesn't necessarily mean it's a valid IRC *protocol* command. When you do `/msg nickserv identify pw` for example, the resulting IRC command sent is `PRIVMSG identify pw`. On some networks the equivalent to activating a vhost would be messaging a specific user, i.e. `PRIVMSG hostserv on`.

**Comment by Throne3d** [comment]
HexChat does seem to give the raw for `/vhost username password` as `vhost username password` (and `/VHOST username password` as `VHOST username password` – perhaps it defaults to sending it raw if the command doesn't exist). In addition, if I use a command of `['VHOST', 'username password']` I do get a response back from the server (via notice) telling me it's the wrong password for the username.

(This is why I've asked for debug mode to be enabled, in case they're receiving a notice about an incorrect password or such; it doesn't display without debug mode, not being an error.)

**Comment by Jahner** [comment]
Debug is below. From what I can see it is sending the login and pass as one line and not separate.

Command on the network is /vhost and it shows that but says password is wrong. I verified that login and pass are working by checking the vhost.conf and manually using vhost.


8 May 20:49:41 - Sending irc NICK/USER
info: Connected to Discord
8 May 20:49:41 - SEND: NICK Nick
8 May 20:49:42 - SEND: USER Nick 8 * Nick
8 May 20:49:42 - SEND: PONG 5B352323
info: Connected to IRC
8 May 20:49:42 - MODE: Nick sets mode: +iwx
8 May 20:49:43 - GOT NOTICE from "Global": "[Logon News - Mar 02 2017] Check out some of our community channels! | Space Merchant Realms: #smr | Radio: #eve-radio #newedenradio #subspace-radio | EVE: #eve | Star Trek Online: #sto | Champions Online: #championsonline | CyberNations: #CyberNations | Star Wars: #swtor | Project Terra: #project-terra | Want to be listed? Join #irchelp and let us know"
8 May 20:49:43 - SEND: VHOST :Nick Password
8 May 20:49:43 - GOT NOTICE from "Global": "[Logon News - Mar 02 2017] Coldfront is now The Airlock! Please update your IRC Client to connect to irc.theairlock.net | Facebook: https://www.facebook.com/TheAirlockNet | Twitter: https://www.twitter.com/theairlocknet | Web: http://www.theairlock.net"
8 May 20:49:43 - GOT NOTICE from "NickServ": "This nickname is registered and protected.  If it is your nickname, type /msg NickServ IDENTIFY password.  Otherwise, please choose a different nickname."
8 May 20:49:43 - GOT NOTICE from the server: "*** [vhost] Login for User Password failed - password incorrect"
8 May 20:49:43 - SEND: PRIVMSG Nickserv :ghost Nick Password
8 May 20:49:44 - GOT NOTICE from "NickServ": "You can't ghost yourself!"
8 May 20:49:44 - SEND: NICK Nick
8 May 20:49:44 - SEND: PRIVMSG NickServ :IDENTIFY Password
8 May 20:49:45 - GOT NOTICE from "NickServ": "Password accepted -- you are now recognized."
8 May 20:49:45 - SEND: WHOIS Nick
8 May 20:49:45 - Unhandled message: { prefix: 'alpha.theairlock.net',
  server: 'alpha.theairlock.net',
  command: '379',
  rawCommand: '379',
  commandType: 'normal',
  args: [ 'Nick', 'Nick', 'is using modes +iwrx ' ] }
8 May 20:49:45 - Unhandled message: { prefix: 'alpha.theairlock.net',
  server: 'alpha.theairlock.net',
  command: '378',
  rawCommand: '378',
  commandType: 'normal',
  args:
   [ 'Nick',
     'Nick',
     'is connecting from *@IP_ADDRESS' ] }
8 May 20:49:45 - Unhandled message: { prefix: 'alpha.theairlock.net',
  server: 'alpha.theairlock.net',
  command: '307',
  rawCommand: '307',
  commandType: 'normal',
  args: [ 'Nick', 'Nick', 'is identified for this nick' ] }
8 May 20:49:45 - SEND: JOIN #eve-radio
8 May 20:49:46 - MODE: #eve-radio sets mode: +v
8 May 20:49:46 - SEND: JOIN #eve-radio-ingame
8 May 20:49:46 - SEND: JOIN #er-staff
8 May 20:49:46 - SEND: MODE #eve-radio-ingame 
8 May 20:49:47 - SEND: MODE #er-staff
CyclingPingTimer 0: server silent for too long, let's send a PING
8 May 20:50:02 - SEND: PING 1

**Comment by Throne3d** [comment]
When you login yourself and try using the VHost (or if you were to), would you use `/vhost username password` or… some other message?

I'm not sure why this wouldn't be working.

**Comment by Jahner** [comment]
I do /vhost Login Pass

I'm baffled as well.

**Comment by ekmartin** [comment]
You could try `["VHOST", "Login", "Pass"]` as well - in case the server expects them as separate arguments.

**Comment by Jahner** [comment]
Looks like that did the trick. Have now set it on 5 different relays and is working on all. Thanks for the help from everyone.

**Comment by ekmartin** [comment]
Great!
