### ISSUE TITLE
Irc bot don't join a channel

### ISSUE THREAD

**Issue by Broken-R3D** [reactiflux/discord-irc#234]
I added one irc channel with two discord chans in config, But the irc bot won't join the given channel, also, there is another one channel too that is linked with two discord channels, but there is nothing wrong with it.. help me please

The response is,
```
8 May 11:45:11 - SEND: PRIVMSG #channel :<05nick> its on other server
error: Received error event from IRC prefix=irc.rizon.io, server=irc.rizon.io, command=err_cannotsendtochan, rawCommand=404, commandType=error, args=[Bridger, #channel, Cannot send to channel]
```

changed channel and nick here :dango:

**Comment by Throne3d** [comment]
It might help to also present your config file.

I think IRC channels can mute who can speak in them, or restrict it to voice-only users? Is that relevant?

**Comment by Broken-R3D** [comment]
@Throne3d Bot have access on that channel plus it was working well just before added a new entry to channelmapping

**Comment by Throne3d** [comment]
… But there is clearly something different between the two situations, if it works in one and not the other, and you haven't given me enough information to figure what the difference is. That's why I asked for the config.

**Comment by Broken-R3D** [comment]
@Throne3d here

```
{
    "nickname": "Bridger",
    "server": "irc.rizon.net",
    "discordToken": "MzA1NzY4NDYwNDQ3Nzc2Nzcx.C-EzUw.qZs8ezdHUvwonliP3yfnrZcfUZI",
    "autoSendCommands": [
        [
            "PRIVMSG",
            "NickServ",
            "IDENTIFY 1212siya"
        ],
        [
            "MODE",
            "Bridger",
            "+x"
        ]
    ],
    "channelMapping": {
        "285467517642866698": "#india.suna",
        "306487320285282305": "#sec.india",
        "306897136480550912": "#kpp99",
        "306897685322137600": "#h20",
        "306902216659304448": "#bridge",
        "306488307754336267": "#17",
        "310680457098297346": "#inferna.uk",
        "310717382689554432": "#suna-algeria",
        "311069420325830656": "#bridge",
        "311084209232150528": "#h20",
        "272127779850420234": "#shadow.company",
        "272086237970563075": "#refugia.bulgaria"
    },
    "ircOptions": {
        "floodProtection": false,
        "floodProtectionDelay": 1000,
        "debug": true
    },
    "format": {
        "commandPrelude": "Command sent by {$nickname}",
        "ircText": "<{$displayUsername}> {$text}",
        "urlAttachment": "<{$displayUsername}> {$attachmentURL}",
        "discord": "**<{$author}>** {$withMentions}"
    },
    "ircNickColor": true,
    "commandCharacters": [
        "!"
    ],
    "ircStatusNotices": true
}

```

**Comment by Throne3d** [comment]
And which of those work(s) with duplicates? I think I'm somewhat surprised it would work at *all* with duplicates.

**Comment by Kakkela** [comment]
You should edit token and identity pw here

**Comment by Broken-R3D** [comment]
There was a duplicate for #refugia.bulgaria earlier.. Now I removed it @Throne3d

**Comment by Throne3d** [comment]
So which of `#bridge` and `#h20` work…?

**Comment by Broken-R3D** [comment]
@Throne3d #H20 works but #Bridge does not

**Comment by Throne3d** [comment]
So it looks like `#Bridge` voices people when they join; are you *sure* the bot is being voiced appropriately?

As a side-note, you will probably encounter weird behavior using two discord channels for a single IRC channel. Messages on the discord side will be mirrored to IRC fine, but messages from IRC will only be mirrored back to one of the discord channels.

**Comment by Broken-R3D** [comment]
@Throne3d Like I said, the bot have access on `#Bridge`. The thing is, the bot doesn't even join the channel when I launch it. So it seems is not a problem with voice

**Comment by Throne3d** [comment]
Fixed. Bot was banned from channel.

**Comment by Broken-R3D** [comment]
@Throne3d Sorry to even make this thread, <3 Thanks and sorry
