### ISSUE TITLE
Ability to block pattern/list of discord users to ignore for bridge transmission

### ISSUE THREAD

**Issue by ensiform** [reactiflux/discord-irc#236]
This would be useful to for example block other bots that send walls of text for output so they don't make floods in an IRC channel resulting in ban/kick/timeout etc.

**Comment by hurburd** [comment]
would come in really handy. maybe a whitelist / blacklist and ability to block messages from one side completely, to use it as irc-bot relay only.

**Comment by anirbanmu** [comment]
+1 this would be very useful in ignoring spammy bots. I might work on this if I get a bit of time.
