### ISSUE TITLE
NPM not updating past 2.1.6

### ISSUE THREAD

**Issue by StrangelyRaidur** [reactiflux/discord-irc#238]
I'm hoping this is an easy one, or just me being stupid, but for some reason, when I run npm update -g discord-irc, or npm install -g discord-irc (after uninstalling), I only get version 2.1.6
Am I doing something wrong?

**Comment by ekmartin** [comment]
Hm, try running `npm uninstall -g discord-irc` first maybe? If that doesn't work you can try `npm cache clean`.

**Comment by StrangelyRaidur** [comment]
Ugh, looks like it was my fault.. somehow I had both a global and a local version installed. The local is what was running. Managed to uninstall both and then install the latest version. Another issue/question coming though.
