### ISSUE TITLE
Commands to IRC from Discord without announcement

### ISSUE THREAD

**Issue by StrangelyRaidur** [reactiflux/discord-irc#239]
Ok, so as its currently set by default, command characters (such as !) that are set in the config are prefixed by a line saying Command sent from Discord by name:
I know it the current version, it can be changed to something else, but is there a way to omit that entirely, just have it send the command through?

**Comment by StrangelyRaidur** [comment]
In looking through the code, I don't see a way to do it, config-wise, so I just commented out the line that adds the notification line. Would be a nice option to have though.

Oh, and thanks much for your work, We're running 4 or 5 of these right now I think. *grin*

**Comment by ekmartin** [comment]
We could add a check around [here](https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L267-L268) so it only posts the prelude if it exists. That way you could set `format.commandPrelude` to an empty string/something false and it'll be disabled.

**Comment by StrangelyRaidur** [comment]
No rush, since I just quoted out line 268 and it works fine for my uses, but its something to consider in a future update.
