### ISSUE TITLE
Keepnick feature for the IRC connection

### ISSUE THREAD

**Issue by rnyberg** [reactiflux/discord-irc#240]
As is with IRC-connections, sometimes the bot ends up disconnecting due various reasons. Seems like the bots then increments it's nick by one number, so "bot" becomes "bot1", "bot2" and so forth the longer it's online.

Would be nice if the bot could check for the availability of the configured nickname on certain intervals, and change it's nick to it once it's available.

**Comment by Throne3d** [comment]
This seems to me like a feature that the upstream library [irc-upd](https://github.com/Throne3d/node-irc) should implement (which I just took over), so I've made a bug there for it (https://github.com/Throne3d/node-irc/issues/15).

**Comment by Throne3d** [comment]
Upstream issue is now closed – I'll close this when a new version of the upstream is pushed?

**Comment by Throne3d** [comment]
Fixed in 2.4.2
