### ISSUE TITLE
Taking ages to connect to IRC, if at all

### ISSUE THREAD

**Issue by metal-crow** [reactiflux/discord-irc#242]
As the title says, having an issue setting up the program. Installed on Ubuntu 16.04, npm version 4.2.0 and nodejs version 7.10.0. Ran `npm install -g discord-irc` (which did give a few unmet peer dependency warnings for erlpack, node-opus, opusscript, and uws), and setup the config file as
```
[
  {
    "nickname": "Relay-Bot",
    "server": "irc.freenode.net",
    "discordToken": "TOKEN",
    "autoSendCommands": [ 
      ["PRIVMSG", "NickServ", "IDENTIFY PASSWORD"]
    ],
    "channelMapping": {
      "#DISCORD": "#IRC"
    }
  }
]
```

When run as `discord-irc --config irc-config.json`, it nearly immediately logs "info: Connected to Discord", but then does nothing for an extremely long time. It did connect to IRC once after 10 minutes, but i have not been able to replicate this.

**Comment by ekmartin** [comment]
discord-irc doesn't really do much in terms of IRC - it relies on [node-irc](https://github.com/martynsmith/node-irc) for that. If you run the bot with `NODE_ENV=development discord-irc --config ...` and set `"ircOptions": { "debug": true } }` in your config you should see some more debug output though, which might help you locate the issue.

**Comment by metal-crow** [comment]
Ah yep, that definitely helps me. It gives the error `GOT NOTICE from the server: "*** Notice -- You need to identify via SASL to use this server"`, which just looks like i have to add `sasl: true, password:PASSWORD` to the ircOptions. Thank you! Might be advisable to add the debugging options to the readme, but my issue can be closed.

**Comment by ekmartin** [comment]
Yes, that's a good idea. Feel free to send a PR if you've got time!
