### ISSUE TITLE
Enable IRC timestamps in Discord chat

### ISSUE THREAD

**Issue by TC01** [reactiflux/discord-irc#244]
I just started using this project; it's a really neat piece of software.

One thing that a user on the Discord side of the bridge suggested is: it would be really nice if there was an option to turn on timestamps in the messages that get sent to Discord. Otherwise it can be difficult to figure out how long ago a conversation on IRC actually happened. It doesn't look like this is already possible to do with the custom formatting options, but it's possible I'm mistaken?

This doesn't seem like it would be too hard to implement, but my nodejs isn't very good and I don't know if I'll have the time to try working on it myself, so I figured I'd file a ticket.

**Comment by ekmartin** [comment]
Why aren't the Discord timestamps themselves enough? Messages should only be relayed right when they're posted anyway, so the timestamp of the Discord message itself should be pretty much correct?

**Comment by ekmartin** [comment]
Ah, I see. This might be something that's resolved using webhooks, see #230 - since that would give each post a different username.

**Comment by TC01** [comment]
Oh, neat. Yeah, I think that would solve the problem.

**Comment by ekmartin** [comment]
I'll close this in the meantime then, as I think timestamps might be a bit too obstructive nonetheless (even with a config option).
