### ISSUE TITLE
install fails on debian 8: EINVAL: invalid argument, chown '/usr/lib/node_modules...

### ISSUE THREAD

**Issue by basisbit** [reactiflux/discord-irc#248]
I just set up a new debian 8 minimal vm, updated it, installed nodejs 8 from official nodejs repo and then tried to install discord-irc using npm. It failed with the following "error messages":

npm ERR! path /usr/lib/node_modules/.staging/cookiejar-79db24e2
npm ERR! code EINVAL
npm ERR! errno -22
npm ERR! syscall chown
npm ERR! EINVAL: invalid argument, chown '/usr/lib/node_modules/.staging/cookiejar-79db24e2'

Any idea what could be the problem?

**Comment by basisbit** [comment]
I guess this happens because of the debian install running in an unprivileged linux container. So most likely the same problem will happen in a docker container.

**Comment by ekmartin** [comment]
You need to set your global npm installation destination to somewhere that you have access to, i.e. by doing something like this: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

There's some other options here as well: https://gist.github.com/isaacs/579814
Or you can use something like nvm: https://github.com/creationix/nvm

**Comment by basisbit** [comment]
I was executing this as root inside an unprivileged linux container. Other npm packages work just fine.

**Comment by basisbit** [comment]
that root user has full everything & all rights on that folder.

**Comment by ekmartin** [comment]
Hm, sorry. It seems a bit similar to [this](https://github.com/yarnpkg/yarn/issues/918#issuecomment-257368242) yarn issue, but not sure.

discord-irc really doesn't do anything strange or uncommon compared to other npm packages though, so this seems to be more of an npm issue in general?
