### ISSUE TITLE
Unexpected Token in multiple places

### ISSUE THREAD

**Issue by ZachySwag** [reactiflux/discord-irc#261]
I'm new to programming, and I was simply trying to make a bot for my new discord server. I followed an online tutorial exactly, and it doesn't run. When I run the command "node index.js" in terminal, it gives me this error:

`SyntaxError: Unexpected token :`
   ` at createScript (vm.js:56:10)`
   ` at Object.runInThisContext (vm.js:97:10)`
   ` at Module._compile (module.js:542:28)`
   ` at Object.Module._extensions..js (module.js:579:10)`
   ` at Module.load (module.js:487:32)`
   ` at tryModuleLoad (module.js:446:12)`
   ` at Function.Module._load (module.js:438:3)`
   ` at Module.runMain (module.js:604:10)`
   ` at run (bootstrap_node.js:389:7)`
   ` at startup (bootstrap_node.js:149:9)`

I have no idea what I'm doing wrong, and if someone could help me that would be great!

Also, I'm using a Mac on MacOS Sierra if that helps at all.

**Comment by Throne3d** [comment]
Uh – is this meant to be filed against https://github.com/hydrabolt/discord.js instead? This package, discord-irc, is specifically a bot to bridge messages between Discord and IRC.

It also might help to show the relevant lines (probably the first few? maybe all of them if you can squish it in pastebin?) of your script – if it's a syntax error, maybe run it through a JavaScript parser somewhere.

**Comment by ekmartin** [comment]
This might also happen if you're trying to run discord-irc with a Node.js version below 6. Try downloading and installing a newer version and try again.
