### ISSUE TITLE
Is it possible to connect to a passworded IRC server?

### ISSUE THREAD

**Issue by jacnoc** [reactiflux/discord-irc#263]
I'm trying to connect the bot to my Twitch IRC channel. But it doesn't seem like it's possible to connect to a passworded IRC server. (Also, it doesn't seem like it's possible to connect using SSL?)

**Comment by Throne3d** [comment]
Using SSL should be possible by setting `secure: true` inside `ircOptions`, as described [here](https://node-irc-upd.readthedocs.io/en/latest/API.html#irc.Client)? A password should be possible to specify similarly, I think?

**Comment by ekmartin** [comment]
Connecting to Twitch should work - see here: https://github.com/reactiflux/discord-irc/issues/42#issuecomment-205241293

Maybe we should add a comment about this to the README/wiki - it has come up a few times.

**Comment by ekmartin** [comment]
Also this might be useful once you get it working: https://github.com/reactiflux/discord-irc/issues/56#issuecomment-211269871

**Comment by jacnoc** [comment]
I feel like an idiot for not looking through closed issues. So yes please add it to the readme/wiki to prevent this happening to future people :)

Any idea what's causing this? 
`joshua@ramnode:~/discord-irc$ ./start.sh
info: Connected to Discord
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
info: Connected to IRC
(node:650) Warning: Possible EventEmitter memory leak detected. 11 whois listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by Throne3d** [comment]
I think it's already in the README, if you look at the IRC options?

That would look like you're being disconnected somehow. The eventemitter memory leak thing is an issue I haven't managed to reproduce yet. If you try enabling debug mode in the `ircOptions` object and also setting the environment variable `NODE_ENV=development` then the logs might contain something that we can use to track it down.
