### ISSUE TITLE
[Suggestion] node-irc

### ISSUE THREAD

**Issue by davericher** [reactiflux/discord-irc#269]
I maintain a fork, could save you some time https://github.com/funsocietyirc/node-irc

**Comment by Throne3d** [comment]
We've already swapped over to [irc-upd](https://github.com/Throne3d/node-irc), a fork that I maintain, actually?

**Comment by davericher** [comment]
Most of them are just re-implementations of the pr's that have been sitting idle on the main repo. Lol just a suggestion.
