### ISSUE TITLE
Twitch chat messages not showing in discord channel

### ISSUE THREAD

**Issue by StreamersConnected** [reactiflux/discord-irc#274]
Hello I've set it up to for messages to show when you type in each chat and for them to show up in both channels (discord/twitch channel) But for some reason it's only showing the messages typed in the discord channel, and not the twitch channel. Please help.

I'm using 
`[{
 	"nickname": "--username--",
 	"server": "irc.chat.twitch.tv",
 	"discordToken": "--token--",
 
	"channelMapping": {
		"--discordChannelID--": "--IRCChannel"

	},
	"ircOptions": {
		"userName": "--username--",
		"password": "oath:--token--"
	},
	"format": {

		"commandPrelude": "Command sent by {$nickname}",
		"ircText": "<{$displayUsername}> {$text}",
		"urlAttachment": "<{$displayUsername}> {$attachmentURL}",
		"discord": "**<{$author}>** {$withMentions}"

	},
	"ircNickColor": false,
	"commandCharacters": ["!", "."],
	"ircStatusNotices": true
}]`

It may be similar to this https://github.com/reactiflux/discord-irc/issues/112

It's sending messages to twitch chat, but twitch chat messages aren't sending to discord.

**Comment by Throne3d** [comment]
Does it do this at startup immediately or only after some period of time? Are you on the latest version? Could you try enabling debug mode as detailed here (https://github.com/reactiflux/discord-irc/issues/265#issuecomment-313925661) and see if there are any log messages?

**Comment by StreamersConnected** [comment]
It does this on start immediately, the messages from twitch chat do not show at all, regardless of when they were sent. I'am on the latest version as this is the first time I've downloaded this on an Linux/Ubuntu VM. And when I do try adding that I cannot start the config file for some reason. I just get this

`

> discord-irc@2.4.1 start /var/www/discord-irc
> node dist/index.js "--config" "config.json"

/var/www/discord-irc/dist/cli.js:48
      throw new _errors.ConfigurationError('The configuration file contains invalid JSON');
      ^

ConfigurationError: The configuration file contains invalid JSON
    at readJSONConfig (/var/www/discord-irc/dist/cli.js:48:13)
    at Object.run [as default] (/var/www/discord-irc/dist/cli.js:62:98)
    at Object.<anonymous> (/var/www/discord-irc/dist/index.js:23:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-irc@2.4.1 start: `node dist/index.js "--config" "config.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-irc@2.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daddy/.npm/_logs/2017-07-21T11_52_53_976Z-debug.log
daddy@streconn:/var/www/discord-irc$
`

**Comment by Throne3d** [comment]
Could you please show the line of the configuration you added? "ircOptions" should be in quotes and you need a comma on the previous line - maybe there's some other syntax thing you're missing.

**Comment by Throne3d** [comment]
(Also "debug" should be in quotes, and to do a block of code in Markdown you need three backticks at the start and end of the block, not just one.)

**Comment by StreamersConnected** [comment]
Alright apologies, I've gotten the debug working correctly now. And I typed a few messages in the twitch chat that I'm currently in and it's showing this

```
CyclingPingTimer 0: server silent for too long, let's send a PING
21 Jul 13:09:48 - SEND: PING 1
21 Jul 13:09:51 - SEND: PRIVMSG #streamersconnected :<NightVillain> tttt
CyclingPingTimer 0: server silent for too long, let's send a PING
21 Jul 13:10:04 - SEND: PING 2
CyclingPingTimer 0: server silent for too long, let's send a PING
21 Jul 13:10:19 - SEND: PING 3

```

**Comment by StreamersConnected** [comment]
Now it's just spamming ```CyclingPingTimer 0: server silent for too long, let's send a PING
21 Jul 13:10:19 - SEND: PING 3``` over and over again with different ping numbers.

**Comment by StreamersConnected** [comment]
It show's these but the messages are still not displaying from twitch chat.

**Comment by Throne3d** [comment]
Does it work if you make the channel name lowercase? I assume it's not already and in my testing it works when it's lowercase and not when I use uppercase. (I'm investigating the problem further to see if I can fix that.)

**Comment by Throne3d** [comment]
… Yeah, when I connect with HexChat and have any uppercase letters in the channel name, Twitch doesn't send or receive my messages. I think it's a problem on their end.
