### ISSUE TITLE
[Enhancement] Grab userlist

### ISSUE THREAD

**Issue by tusing** [reactiflux/discord-irc#28]
I've been using this for one of our communities and it's working well, so far.

It would be neat if we could grab the list of users on the other platform, so Discord users would not have to log in to IRC to see who is online, and vice versa.

**Comment by ekmartin** [comment]
Even though I see how this could be useful I think adding a concept of commands to the discord-irc bot is a bit out of scope. The cleanest way to implement it would probably be through private messages to the bot, but even that would still be quite ugly when you have multiple channels per bot and similar.

I'm going to close this, but I'd be open to reconsideration if it's considered necessary by more people. Nonetheless it shouldn't be too hard to implement in a fork, so I'd recommend giving it a try!
