### ISSUE TITLE
Discord Channel -to- IRC PM (and back)

### ISSUE THREAD

**Issue by RheaAyase** [reactiflux/discord-irc#280]
As funny or weird it may sound, I actually have a use-case for this and am willing to look into implementation (I don't have much time and don't know much about nodejs tho.) It would be appreciated if there was anyone who would like to throw me a hint or two as to where to look. The bot currently PMs me correctly when I simply enter nickname instead of IRC channel into the configuration, but it ain't workin' the other way around - the PM is just logged. I would enter a check for the configuration and proceed with posting the message on Discord if it's a PM from matching _nick/channel._

![](https://cloud.rhea-ayase.eu/s/83t6fjqecBofIph/download)

Should you wish to lend a hand, feel free to get in touch on Freenode (`Rhea`) or Discord (`Rhea#0321`)

**Comment by ekmartin** [comment]
I think this might be a bit out of scope for the core project, so gonna close this. Should be doable in a fork though!

**Comment by ClobberXD** [comment]
This should be doable without any modifications to the bot, by setting the channel mapping in config.json, as both channel messages and private messages use the same IRC command 'PRIVMSG' as mentioned here - https://tools.ietf.org/html/rfc1459.html#section-4.4

I'm still having trouble with it though, as I keep getting invalid channel name error... I'll continue to post updates here, for the OP and all others who might encounter the same problem in the future.

**Comment by ClobberXD** [comment]
Oh I see. It'd be useful to have that capability as well...

By the way, could you show me the exact format of the target which is a user?
