### ISSUE TITLE
/dist/bot.js:127  -- SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by DMahalko** [reactiflux/discord-irc#283]
**I am a node.js novice trying to get this working on Ubuntu.**

**After much fooling around I finally got it to compile, mostly, but it is now dying at "npm start"**

**Ubuntu preparation to make it go:**
`sudo ln -s /usr/bin/nodejs /usr/bin/node`
`sudo apt-get install libicu-dev`
`sudo apt-get install autoconf`
`sudo apt-get install autotools-dev`
`sudo apt-get install libtool`

**It is cranky at the end but I think I can ignore warnings?**
`lib/bot.js -> dist/bot.js`
`lib/cli.js -> dist/cli.js`
`lib/errors.js -> dist/errors.js`
`lib/formatting.js -> dist/formatting.js`
`lib/helpers.js -> dist/helpers.js`
`lib/index.js -> dist/index.js`
`lib/validators.js -> dist/validators.js`
`discord-irc@2.4.1 /home/somebody/discord-irc-master`
`├── bufferutil@3.0.2  extraneous`
`├── erlpack@0.1.0  extraneous (git://github.com/hammerandchisel/erlpack.git#ad84c69355f03770a84d4bd8a20b981dd168fcf4)`
`├── libsodium-wrappers@0.5.2  extraneous`
`├── node-opus@0.2.6  extraneous`
`├── opusscript@0.0.3  extraneous`
`├── sodium@2.0.1  extraneous`
`└── uws@0.14.5  extraneous`
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2`

**Okay first launch time:**
npm start
`> discord-irc@2.4.1 start /home/somebody/discord-irc-master`
`> node dist/index.js`
` `
`/home/somebody/discord-irc-master/dist/bot.js:127`
`        this.ircClient.send(...element);`
`                            ^^^`
` `
`SyntaxError: Unexpected token ...`
`    at exports.runInThisContext (vm.js:53:16)`
`    at Module._compile (module.js:374:25)`
`    at Object.Module._extensions..js (module.js:417:10)`
`    at Module.load (module.js:344:32)`
`    at Function.Module._load (module.js:301:12)`
`    at Module.require (module.js:354:17)`
`    at require (internal/module.js:12:17)`
`    at Object.<anonymous> (/home/somebody/discord-irc-master/dist/helpers.js:12:12)`
`    at Module._compile (module.js:410:26)`
`    at Object.Module._extensions..js (module.js:417:10)`
` `
`npm ERR! Linux 4.4.0-59-generic`
`npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"`
`npm ERR! node v4.2.6`
`npm ERR! npm  v3.5.2`
`npm ERR! code ELIFECYCLE`
`npm ERR! discord-irc@2.4.1 start: 'node dist/index.js'`
`npm ERR! Exit status 1`

**I have no idea how to proceed from here.**

**Comment by Throne3d** [comment]
That looks like it hasn't transpiled properly. Did you clone the repo then do as in the README, or did you attempt to install the git repo directly using `npm`? I think there are issues with the latter, but I'm not sure what.

**Comment by ekmartin** [comment]
You need node.js version 6 or higher (https://github.com/reactiflux/discord-irc#installation-and-usage). Installation instructions: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

Maybe we should add a check for it index.js or something, since [https://github.com/reactiflux/discord-irc/blob/master/package.json#L14](https://github.com/reactiflux/discord-irc/blob/master/package.json#L14) only really work when you install it globally.
