### ISSUE TITLE
Ubuntu Cronjob setup discord-irc not found?

### ISSUE THREAD

**Issue by LigerXT5** [reactiflux/discord-irc#285]
I can run the command as either my normal user, or under root.

discord-irc --config /home/User/Streaming/discord-irc/config.json

However, running this command as a cron job (setup through webmin). I get the following error when the cronjob is ran.

/bin/sh: 1: discord-irc: not found

I can set the cron job to run under my user account, or as root, no difference.

Edit: I've also attempted running it under screen. Same results.
screen -dmS discord-irc && screen -S discord-irc -X stuff "discord-irc --config /home/User/Streaming/discord-irc/config.json^M"

**Comment by mekolat** [comment]
Make sure discord-irc is in your PATH and that it was installed with the `-g` flag. If it is not in your path, you could try adding this line to your crontab:
```crontab
@reboot /usr/local/bin/discord-irc --config /home/User/Streaming/discord-irc/config.json
```
It will start discord-irc from its global install path every time you boot your machine
