### ISSUE TITLE
Disconnect without reconnect. Possibly SSL/TLS related?

### ISSUE THREAD

**Issue by Peppernrino** [reactiflux/discord-irc#288]
i am getting this error:

> info: Connected to Discord
info: Connected to IRC
XX Aug XX:XX:XX - Non-latest connection is being discarded, not reconnected
error: Received error event from Discord Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:610:25)
error: Received error event from Discord Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:610:25)
info: Connected to Discord
error: Received error event from Discord Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ekmartin** [comment]
Could you try running your bot with tee environment variable `NODE_ENV` set to `development`? I.e. `NODE_ENV=development discord-irc ...`. That will give us some more debug information.

**Comment by Peppernrino** [comment]
update:
i've got it working, but it still disconnects every once in a while.

CyclingPingTimer 0: server silent for too long, let's send a PING
6 Sep 16:04:22 - SEND: PING 5587
CyclingPingTimer 0: server silent for too long, let's send a PING
6 Sep 16:04:37 - SEND: PING 5588
CyclingPingTimer 0: server silent for too long, let's send a PING
6 Sep 16:04:59 - SEND: PING 5589
CyclingPingTimer 0: server silent for too long, let's send a PING
6 Sep 16:05:15 - SEND: PING 5590
CyclingPingTimer 0: ping timeout!
6 Sep 16:05:23 - Connection got "close" event
6 Sep 16:05:23 - Non-latest connection is being discarded, not reconnected

i have even included a retryCount/retryDelay in my json file, to no avail.

**Comment by Throne3d** [comment]
Did you also set `autoRejoin` to true?

**Comment by Peppernrino** [comment]
hm... lol. i will now. :D

**Comment by Peppernrino** [comment]
uh... it disconnected with:
`  "ircOptions": {
    "autoRenick": "false",
    "autoRejoin": "true",
    "retryCount": "10",
    "retryDelay": "10000",
    "sasl": "true"`

21 Sep XX:XX:XX - Connection got "close" event
21 Sep XX:XX:XX - Non-latest connection is being discarded, not reconnected

bump? ;)

**Comment by Throne3d** [comment]
uh, oops, I was wrong about `autoRejoin` anyway – doesn't do what I thought it did.

Is it definitely not reconnecting at all? You've set a specific `retryCount` so if it _gets_ to that value I'd expect it to stop?

**Comment by Peppernrino** [comment]
it actually doesn't try at all when experiencing this issue. the `retrycount` appears to only work when initially connecting. i noticed when i was having my SASL "troubles".

**Comment by Throne3d** [comment]
I've definitely had `retryCount` work at other times (like, just now, when I flipped my internet off while the bot was running), so I don't know why that would be. I thought it might be something to do with SASL, but just tried connecting to freenode with it enabled and it's definitely trying to reconnect on this too.

Honestly I'm not sure.

**Comment by Peppernrino** [comment]
maybe less to do with the internet connection, and more with the ping receiving some kind of disconnect signal? have you had any luck adjusting the ping timers?

**Comment by Throne3d** [comment]
… I'm not sure what you mean? I disabled my internet while it was running, it got a ping timeout, it kept trying to reconnect – the last step in this process is what yours seems *not* to be doing, for some unknown reason.

`Non-latest connection is being discarded` indicates that the library had another connection to the server ongoing when one connection broke, meaning it should already be reconnecting.

**Comment by ensiform** [comment]
I still get drops with this on my home network because my router goes haywire a lot even with ethernet. It does not seem to reconnect or if its down long enough it doesn't attempt to return once internet is restored.

**Comment by Throne3d** [comment]
Is this still a problem with the latest version? The upstream IRC library was updated quite a bit and *might* have fixed this.

**Comment by Peppernrino** [comment]
so far, setting my ping a bit higher has been super successful, but i'll install the new version when i update my bot. :) been playing around with some of the new irc-upd options.

>"retryCount": "10",
"retryDelay": "10000",
"millisecondsOfSilenceBeforePingSent": "600000",

**Comment by doublehelix457** [comment]
I will try this suggestion, thank you @Peppernrino

**Comment by Peppernrino** [comment]
updated to 2.4.1

**Comment by Throne3d** [comment]
A lot of these options were around in the old node-irc but (for some reason) not documented. I'm not really sure why, but added them to the documentation when I forked it.

You probably don't want speech marks around the _values_ there, since they're supposed to be integers (though Javascript often treats them the same way) – that part of the config should be:

```js
"retryCount": 10,
"retryDelay": 10000,
"millisecondsOfSilenceBeforePingSent": 600000,
```

(600,000 seems rather high and `millisecondsOfSilenceBeforePingSent` just reduces how frequently it checks for a ping, which will reduce the occurrence of this but probably not actually stop it. If it works for you that's good but you might just want to try, say, `60 * 1000`, for sixty seconds, and see how that works? The default is 15 seconds, so that's quite a bump anyway. You may also find `millisecondsBeforePingTimeout` useful – maybe doubling it to `16 * 1000`.)

**Comment by Peppernrino** [comment]
i was thinking maybe the ping was too often, and by making it a huge stretch of time, i wouldn't risk getting a scrape error or something like that. maybe the bot pings discord too much as default? this is all speculation... just getting the brain juices going. :)

also, i tried with`millisecondsBeforePingTimeout` and it didn't seem to make as much of a dent in performance as `millisecondsOfSilenceBeforePingSent`.

**Comment by Throne3d** [comment]
Hmm. My IRC client (HexChat) sends a ping about every 30 seconds, and the IRC library is set to ping every 15 seconds, but I don't actually encounter any issues while running it, and I'd expect that if a lot of people had this problem we'd hear about it more. (The bot doesn't seem to time out on a Discord ping failure, and the setting you're changing is for IRC, so I assume you mean "maybe the bot pings IRC too much as default"?)

**Comment by Peppernrino** [comment]
it drops from Discord. lol, i have no idea why changing the IRC options make any difference. but they do.

**Comment by andruwne** [comment]
Have you verified if that port requires a secure connection?

**Comment by Throne3d** [comment]
I'm going to close this for now. If the issue persists, please re-open it (hopefully with more information!).
