### ISSUE TITLE
Discord-IRC sends messages in one direction, not both.

### ISSUE THREAD

**Issue by CallMeM** [reactiflux/discord-irc#29]
I've successfully got the bot to appear online in Discord and join in IRC, but the first bridge I tried would only send messages from IRC to Discord, but not the other way around. I tested with a new bridge with another channel and server, but that one only sends messages from Discord to IRC, and again, not the other way around. Sometimes, it will send both ways, but it doesn't consistently happen. I can't seem to find what causes this, very confused.

**Comment by ekmartin** [comment]
Could you post a stripped down version of the configuration you're attempting to use?
Also, what Node version are you using? `node --version`

**Comment by CallMeM** [comment]
Config:
```
[
  {
    "nickname": "[Discord]",
    "server": "irc.server.com",
    "discordEmail": "email@mail.com",
    "discordPassword": "password",
    "autoSendCommands": [
      ["PRIVMSG", "NickServ", "IDENTIFY password"],
      ["MODE", "[Discord]", "+x"]
    ],
    "channelMapping": {
      "#discord1": "#irc1",
      "#discord2": "#irc2"
    }
  }
]
```
`node --version` returns v0.12.9
Pair 1 is the IRC to Discord only, and pair 2 is the IRC to Discord only.

**Comment by CallMeM** [comment]
While experimenting, I changed the channel mapping to:
```json

    "channelMapping": {
      "#discord1": "#irc1",
      "#discord1": "#irc1",
      "#discord2": "#irc2"
    }
```
Right now pair 1 is both ways, but pair 2 is still Discord to IRC only.

**Comment by ekmartin** [comment]
Sorry for the late answer, not sure what might cause this (I'm not able to reproduce the issue myself using Node 0.12). 

If you try `export NODE_ENV=development` before running the application you'll see some more log output though, which might help identifying the issue. Also, is the Discord user you're logging in as in the configuration a member of both the channels?

**Comment by CallMeM** [comment]
Er, sorry for not knowing, but I don't know where the log outputs are, and the Discord user is a member of every channel involved.

**Comment by ekmartin** [comment]
The log output will just be in the terminal where you're running discord-irc. Are you cloning the repository or using a globally installed version of the application? I.e. how are you running the application, using `discord-irc --config config.json`?

**Comment by CallMeM** [comment]
I'm using `discord-irc --config config.json`, but nothing seems to be returned in the terminal.

**Comment by ekmartin** [comment]
If you instead use `NODE_ENV=development discord-irc --config config.json` you should see output similar to this:

![image](https://cloud.githubusercontent.com/assets/3536982/12532502/29ab378e-c216-11e5-8028-e347721741aa.png)

**Comment by CallMeM** [comment]
It's strange, I can't seem to reproduce it consistently either.

**Comment by ekmartin** [comment]
Might be related to #25 if it only happens after a while. Make sure you're running the latest version of discord-irc, `npm update -g discord-irc`. 

It shouldn't matter, but you might try updating to a newer version of Node.js too (0.12 is quite old). If you're using Linux, distributions for most OSs can be found [here](https://github.com/nodesource/distributions).

**Comment by CallMeM** [comment]
I was not aware that there were newer versions of Node.js, I was using 0.10 before I updated to 0.12
