### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by BagiTornado** [reactiflux/discord-irc#290]
For example, if you replace
`Server-starting-message = "** The server is starting! **"`
on
`Server-starting-message = "** Сервер запускаеться! **"`
then the diskord
`"?????? ???????!"`
Is it possible to correct the conclusion?

**Comment by Throne3d** [comment]
This seems likely to be a similar problem to https://github.com/reactiflux/discord-irc/issues/237#issuecomment-322067542. Have you tried installing `iconv` and `node-icu-charset-detector`, then adding `"encoding": "utf-8"` to the `ircOptions` object of your configuration?
