### ISSUE TITLE
Frozen on Sending irc NICK/USER

### ISSUE THREAD

**Issue by deef0000dragon1** [reactiflux/discord-irc#291]
When launched, discord-irc starts and connects to Discord, but stays on 29 Aug 15:43:52 - Sending irc NICK/USER for IRC connection. Several munites later, it connected, but is irratic. 

>discord-irc --config CONFIG
29 Aug 15:43:52 - Attempting socket connection to IRC server
29 Aug 15:43:52 - Socket connection successful
29 Aug 15:43:52 - Sending irc NICK/USER
info: Connected to Discord
info: Connected to IRC
29 Aug 15:50:43 - MODE: USER sets mode: +i
29 Aug 15:50:43 - QUIT:  USER !~ USER @(X.X.X.X) Ping timeout: 264 seconds
29 Aug 15:50:43 - Unhandled message: { command: 'ERROR',
  rawCommand: 'ERROR',
  commandType: 'normal',
  args: [ 'Closing Link: (X.X.X.X) (Ping timeout: 264 seconds)' ] }
29 Aug 15:50:43 - Connection got "end" event
29 Aug 15:50:43 - Connection got "close" event
29 Aug 15:50:43 - Disconnected: reconnecting
29 Aug 15:50:43 - Waiting 2000ms before retrying
29 Aug 15:50:45 - Attempting socket connection to IRC server
29 Aug 15:50:45 - Socket connection successful
29 Aug 15:50:45 - Sending irc NICK/USER
info: Connected to Discord
info: Connected to IRC
29 Aug 15:50:53 - MODE:  USER sets mode: +i
29 Aug 15:51:00 - Unhandled message: { prefix: 'orwell.freenode.net',
  server: 'orwell.freenode.net',
  command: '378',
  rawCommand: '378',
  commandType: 'normal',
  args:
   [ ' USER ',
     ' USER ',
     'is connecting from *@(X.X.X.X) (X.X.X.X)' ] }
29 Aug 15:51:01 - GOT NOTICE from "ChanServ": "MESSAGE"

**Comment by deef0000dragon1** [comment]
Sldo, Bot leaves server after a period of time (1-6 hours). Also random.

**Comment by Peppernrino** [comment]
you should edit out your IP, if that's your real IP, first of all...

secondly, i am getting the unhandled error as well, but my bot connects.

thirdly, the random disconnects are related to discord.js. see #288.

**Comment by Throne3d** [comment]
It looks like you're disconnecting from both Discord and IRC, and I haven't encountered this myself. Are you sure you have a stable internet connection, and it's not just crashing every so often?
