### ISSUE TITLE
Join issue

### ISSUE THREAD

**Issue by steven4547466** [reactiflux/discord-irc#294]
Alright, so I did everything however when I get to inviting it no servers op up, I am signed in and own 3 discords and a bot testing discord and none are showing, any reason why?

**Comment by steven4547466** [comment]
![screenshot_20170903_044630](https://user-images.githubusercontent.com/23726534/30001687-ec7b0232-9062-11e7-95c7-c311f2c5f660.png)

**Comment by Kovaelin** [comment]
Are you sure you changed the client_id part of the url to your own Client ID?
