### ISSUE TITLE
Timeout on connection. Is there way to increase it?

### ISSUE THREAD

**Issue by ontelo** [reactiflux/discord-irc#296]
For some reason connecting to IRC server from my VPS takes bit longer.

Is there way to increase the timeout before disconnection. Now it's too short and I'm not able to connect to IRC-server before it disconnects and starts reconnection cycle.

'Please wait while we process your connection.', takes 15-30 seconds.

4 Sep 13:58:38 - Attempting socket connection to IRC server
4 Sep 13:58:38 - Socket connection successful
4 Sep 13:58:38 - Sending irc NICK/USER
4 Sep 13:58:38 - SEND: NICK XXXXX
4 Sep 13:58:38 - SEND: USER XXXXX 8 * XXXXX
4 Sep 13:58:38 - CyclingPingTimer 0: ping timer started
4 Sep 13:58:38 - Received: :eris.us.ircnet.net 020 * :Please wait while we process your connection.
4 Sep 13:58:38 - ERROR: Unhandled message: { prefix: 'eris.us.ircnet.net',
  server: 'eris.us.ircnet.net',
  command: '020',
  rawCommand: '020',
  commandType: 'normal',
  args: [ '*', 'Please wait while we process your connection.' ] } 
info: Connected to Discord
**4 Sep 13:58:53 - CyclingPingTimer 0: server silent for too long, let's send a PING
4 Sep 13:58:53 - SEND: PING 1
4 Sep 13:59:01 - CyclingPingTimer 0: ping timer stopped
4 Sep 13:59:01 - CyclingPingTimer 0: ping timeout!
4 Sep 13:59:01 - Connection got "close" event
4 Sep 13:59:01 - Disconnected: reconnecting**
4 Sep 13:59:01 - Waiting 10000ms before retrying

**Comment by Throne3d** [comment]
It's apparently an undocumented feature of the upstream IRC library, but there's `millisecondsOfSilenceBeforePingSent` and `millisecondsBeforePingTimeout` available in the `ircOptions` hash – these default to 15,000 and 8,000 respectively, and you should be able to change the first to help here?

**Comment by jarkkombrain** [comment]
Wow, that was fast reply. It worked. 

Thanks a lot.

**Comment by Throne3d** [comment]
No problem! I'll look into documenting it upstream.
