### ISSUE TITLE
Wait until registered

### ISSUE THREAD

**Issue by Peppernrino** [reactiflux/discord-irc#297]
I have trouble joining some IRC rooms that require registration (+r).

Is there a way we could introduce a 'wait-until' function, so it will wait until registered with NickServ to join a room? https://www.npmjs.com/package/wait-until

**Comment by Madbrad200** [comment]
Can't you authenticate with SASL? It does exactly that.

**Comment by Peppernrino** [comment]
haven't quite figured out SASL, but i'll get back to you. :)

**Comment by Peppernrino** [comment]
awesome. followed advice here: https://github.com/reactiflux/discord-irc/issues/242 and i'm all set up. now to figure out OpenSSL... thank you for your time and help. :)

**Comment by dustwolf** [comment]
This solution doesn't appear to work if you just need password authentication and no SASL.
