### ISSUE TITLE
Multicharacter command characters

### ISSUE THREAD

**Issue by xbony2** [reactiflux/discord-irc#299]
I put
```json
"commandCharacters": ["@@", "$"]
```
in my config, and it works fine for the prefix $ but not the prefix @@, as it's more than one character. I know it's a rare case but I'm using 2 characters as the input character for my bot, shouldn't be too hard to fix.

**Comment by mekolat** [comment]
```patch
diff --git a/lib/bot.js b/lib/bot.js
index 2587178..6de8fc7 100644
--- a/lib/bot.js
+++ b/lib/bot.js
@@ -248,7 +248,7 @@ class Bot {
   }

   isCommandMessage(message) {
-    return this.commandCharacters.indexOf(message[0]) !== -1;
+    return message.startswith(tuple(this.commandCharacters));
   }

   static substitutePattern(message, patternMapping) {
```

**Comment by ekmartin** [comment]
Definitely open to merging a PR that fixes this :) `this.commandCharacters.some(prefix => message.startsWith(prefix))` should do the trick
