### ISSUE TITLE
Problem with terminal readout when modes are being enabled?

### ISSUE THREAD

**Issue by Peppernrino** [reactiflux/discord-irc#304]
I have `  "autoSendCommands": [
    ["MODE", "botname", "+RZi"]
  ],` in my config.

I get some unhandled errors while connecting to IRC:

`Unhandled message: { prefix: 'wilhelm.freenode.net',
  server: 'wilhelm.freenode.net',
  command: '900',
  rawCommand: '900',
  commandType: 'normal',
`

`Unhandled message: { prefix: 'wilhelm.freenode.net',
  server: 'wilhelm.freenode.net',
  command: '378',
  rawCommand: '378',
  commandType: 'normal',
`

is this because modes are failing, or is it just a normal confirmation message the bot can't read?

`21 Sep XX:XX:XX - MODE: botname sets mode: +i
21 Sep XX:XX:XX - SEND: MODE botname +RZi
21 Sep XX:XX:XX - SEND: WHOIS botname
21 Sep XX:XX:XX - SEND: JOIN #channel1
21 Sep XX:XX:XX - SEND: JOIN #channel2
21 Sep XX:XX:XX - SEND: JOIN #channel3
21 Sep XX:XX:XX - MODE: botname sets mode: +R
`

it seems like it's trying to enable modes twice, or maybe the SEND message is just slower to read out from terminal?

**Comment by Throne3d** [comment]
I can't actually tell whether that's a confirmation message or a failure, there – the `rawCommand` value isn't immediately helpful but it should also have a textual message to go with? The bot often does not handle weird messages that servers send – a lot of them seem to be nonstandard.

The bot only seems to be sending your command once? `SEND` shows when the bot sends a command, `MODE` shows when the bot receives a MODE command, and it only sends `+RZi` once there. `+i` is probably enabled by the server by default on connection or something. It looks like the server might be discarding the `Z` you pass it, though.

**Comment by Peppernrino** [comment]
sorry, the `900` is between `SEND: AUTHENTICATE`, and `SEND: CAP`
and the `378` is after `SEND: JOIN`, and before getting voice in channels... perhaps it's the channel topic/motd, etc?

and yes, after a closer look, `Z` does NOT appear anywhere as a `MODE`... after removing it from the config.json, I get the same errors, but the `MODE` output is the same.

**Comment by Peppernrino** [comment]
> 22 Sep XX:XX:XX - SEND: AUTHENTICATE passwordstring
> 22 Sep XX:XX:XX - Unhandled message: { prefix: 'wilhelm.freenode.net',
>   server: 'wilhelm.freenode.net',
>   command: '900',
>   rawCommand: '900',
>   commandType: 'normal',
>   args: 
>    [ 'botname',
>      'botname!botname@IP',
>      'botname',
>      'You are now logged in as botname.' ] }
> 22 Sep XX:XX:XX - SEND: CAP END
> info: Connected to IRC
>

**Comment by Throne3d** [comment]
I think it's just that the library hasn't been told about that yet, then. I'll make an issue to properly handle IRCv3 SASL responses, I guess?
