### ISSUE TITLE
[IRC side] Is there a setting to configure ping<>pong time?

### ISSUE THREAD

**Issue by ensiform** [reactiflux/discord-irc#305]
Right now my git bash shell shows its spamming every 20-30 seconds or so when there's no server activity.

**Comment by Throne3d** [comment]
Yes, there is – see [here](https://node-irc-upd.readthedocs.io/en/latest/API.html#irc.Client), specifically `millisecondsOfSilenceBeforePingSent` and `millisecondsBeforePingTimeout`.

The spamming is a bug that has been fixed in the code, but no updated version has been pushed yet.

**Comment by ensiform** [comment]
But that isn't a setting which is available in the bot's config.json is it?

**Comment by ekmartin** [comment]
You can pass raw options through to node-irc using the `ircOptions` property :)
