### ISSUE TITLE
Filter by user and forward to specific channel

### ISSUE THREAD

**Issue by matkatmusic** [reactiflux/discord-irc#312]
We have a couple bots in an IRC channel for the JUCE c++ framework.  One bot passes the forum's rss feed of new forum threads into the IRC channel.  another bot follows the rss feed for the github repo for the develop branch of the JUCE repository, so whenever the devs update the repo, the updates appear in the IRC channel.   It would be really cool if we could filter specific messages from these bots to go to specific discord messages when bridging between IRC and discord. 

in our case, the bots are called "jugit" for the github bot, and "jubot" for the forum bot.  is it possible to set up some channel mapping like this? 

`if( author == jugit ) { author.message.forwardTo( discordServer[#github-repo] ); }`
`else if( author == jubot ) { author.message.forwardTo( discordServer[#forum] ); }`
`else { author.message.forwardTo( discordServer[#general] ); }`

Perhaps this line: 
https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L128
`this.ircClient.on('message', this.sendToDiscord.bind(this));`
is where the forwarding needs to be addressed? 
if the irc config options could include an array of IRC usernames and Discord channels to send to, that would probably be all that's required as far as getting it working. 

```
"ircOptions": { // Optional node-irc options
      "floodProtection": false, // On by default
      "floodProtectionDelay": 1000, // 500 by default
      //options per irc channel
      "channelOptions" : {
          {
             "channelName": "#juce",
              "forwardedUsers": {
                  "jugit": "#jugit",  //IRC name, discord channel to forward to
                  "jubot": "#jubot",
                  "*": "#general",  //all names except those above 
              }
          },
       }
    },
```

**Comment by ekmartin** [comment]
No, but you could make one IRC channel per bot and have the bots post their updates there as well.
I don't think is generic enough that it needs to be in discord-irc though, sorry! Feel free to ask questions if you want to try implementing it in a fork :)
