### ISSUE TITLE
Cross platform ban.

### ISSUE THREAD

**Issue by maorninja** [reactiflux/discord-irc#317]
Hey, I have a recommendation for this.

Basically, make the bot have a little command where if you type !ban {user} on discord, you can ban them on IRC and vice versa.

And how this works? Well, it basically detects the rank that the user who sent it has and checks if he has the "Ban users" perm. If he has it, and the bot on IRC has the perm to do so as well, it'll ban the user off IRC from Discord. Vice versa as well for IRC -> Discord.

**Comment by ekmartin** [comment]
I think this and other chat commands is a bit too out of scope for this project, sorry! Happy to give pointers if anyone wants to try implementing it in a fork though.
