### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by TLI1233** [reactiflux/discord-irc#335]
Ok, so I open up Node.js command prompt
After navigating to the IRC directory as shown here http://prntscr.com/h94rgk where my config file is located, I do "npm install -g discord-irc"
It returns alot of warns and errors, as seen in this log file 
[Log crash.txt](https://github.com/reactiflux/discord-irc/files/1463887/Log.crash.txt)
and doesn't create anything.
Then I do discord-irc --config config.json (because the config is already in the directory i'm in)
It returns this 
[Log crash 2.txt](https://github.com/reactiflux/discord-irc/files/1463888/Log.crash.2.txt)
and doesn't create anything.

Any help would be appreciated, thanks in advance.

EDIT: Contents of my IRC folder: http://prntscr.com/h94so7

**Comment by Throne3d** [comment]
For the first thing: Do you have Python installed? It seems to be looking for Python 3.5 and can't find it. You might have something misconfigured somewhere.

For the second thing: Your `config.json` file is invalid, somehow – you might have missed a comma or some quote marks. If you pasted that here (**with the token and any passwords removed**) then we could help with that. Alternatively you could try finding an online JSON parser, which might (but probably won't) be able to help.

**Comment by TLI1233** [comment]
http://prntscr.com/h95bdy I have got python, here's the config.
[conffiiig.txt](https://github.com/reactiflux/discord-irc/files/1463922/conffiiig.txt)

**Comment by Throne3d** [comment]
That doesn't quite look like what's in the sample config.

Try:

```json
[
  {
    "nickname": "BotTest",
    "server": "irc.canternet.org",
    "discordToken": "token-here",
    "channelMapping": {
      "#general": "#TLiii"
    }
  }
]
```

Wrt Python, it's probably not in your path. Maybe you unchecked that box when you were installing it. I'd suggest looking in `C:\Users\PC\AppData\Local\Programs\Python\Python35` to see if you have a `python.exe` executable there (or even if the folder doesn't exist) – it seems to be looking there for it.

**Comment by TLI1233** [comment]
I have checked my PATH, the variable of python is in there, and AppData, everything is in there, python.exe and pythonw.exe

**Comment by Throne3d** [comment]
Huh. I'd expect there's a typo or mistake somewhere in the directory structure, then – that even if you have Python in both AppData and your PATH, you've got it in the wrong folder or something – because the installation claims that there is no such file `C:\Users\PC\AppData\Local\Programs\Python\Python35\python.exe`, and I assume it determines this location from your PATH. If that's not the problem, I'd recommend looking somewhere else to get help more generally with `npm install`; this is part of the `node-gyp` automatic installation, which we don't control.

Those two dependencies aren't, however, required for the application to function, if you don't want to worry about them – they're to translate the encoding of certain messages (on the IRC side) so you don't get corrupted characters (specifically around things like `ä`).

**Comment by TLI1233** [comment]
I looked at my PATH and it doesn't look quite right, could you see if something's wrong with it please?
C:\Users\PC\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\PC\AppData\Local\Programs\Python\Python35\;C:\Windows\system32\;C:\Users\PC\AppData\Roaming\npm

**Comment by Throne3d** [comment]
It does contain `C:\Users\PC\AppData\Local\Programs\Python\Python35`, so presumably that's where the installer is getting the directory from. Does that folder exist, if you try to find it? (You said that Python was in your AppData, but is it at that exact location?)

**Comment by TLI1233** [comment]
http://prntscr.com/h95krb
Also, my Windows is in Polish and Users is not users it's Użytkownicy, can that be a problem?

**Comment by Throne3d** [comment]
I'm not sure, but it could be. If you open a command prompt and type in `C:\Users\PC\AppData\Local\Programs\Python\Python35\python.exe`, does python execute? (If not, does `C:\Użytkownicy\PC\AppData\Local\Programs\Python\Python35\python.exe` work, assuming you can type that in?)

**Comment by TLI1233** [comment]
The 1st thing returns this http://prntscr.com/h95mhr, the 2nd doesn't work because the letter ż doesn't work in cmd.

**Comment by Throne3d** [comment]
Since the first thing works, `Users` should work fine. I'm not sure why it doesn't.

It could be because `node-gyp` requires Python 2, instead of Python 3? If you run `npm install --global --production windows-build-tools` (as is found [in the instructions here](https://github.com/nodejs/node-gyp#on-windows)), then try re-running `npm install -g discord-irc`, does that fix it?

**Comment by TLI1233** [comment]
Where do I have to run `npm install --global --production windows-build-tools` In C:\Users\PC or In C:\Users\PC\Downloads\IRC

**Comment by Throne3d** [comment]
It doesn't matter, because it has the `--global` flag.

**Comment by TLI1233** [comment]
I did `npm install --global --production windows-build-tools` It returned a bunch of errors, I won't do the install of discord-irc before you check those out
[Logofbuildtools.txt](https://github.com/reactiflux/discord-irc/files/1463963/Logofbuildtools.txt)

**Comment by Throne3d** [comment]
… I have no idea. Maybe try installing Python 2.7 manually.

**Comment by TLI1233** [comment]
2.7? Okay.
brb

**Comment by TLI1233** [comment]
Do i have to uninstall 3.5 before installing 2.7?

**Comment by Throne3d** [comment]
No, they should be able to live side-by-side. Also this is starting to feel a little like hand-holding, when you could google for these answers.

**Comment by TLI1233** [comment]
Okay, sorry.

**Comment by TLI1233** [comment]
Now, sorry if this is a dumb question, but do I have to add python 2.7 to path too?

**Comment by Throne3d** [comment]
If the installer doesn't give you the option, and it's not in your PATH when you check after that, you probably need to add it.

**Comment by TLI1233** [comment]
Okay, Python 2.7 Reinstalled, do I have to run `npm install --global --production windows-build-tools` again?

**Comment by Throne3d** [comment]
Try to install discord-irc again, and if it errors with the same thing, try installing `windows-build-tools` again, and if that errors with the same thing, I'd suggest you look elsewhere for how to fix that or you just use `discord-irc` without the text encoding translation feature, like I said would be possible earlier.

**Comment by TLI1233** [comment]
Well, I'm out of ideas, any other ways to run IRC?
Nothing worked.

**Comment by Throne3d** [comment]
… What do you mean?

After amending your config.json file as I said earlier, does the command not work (`discord-irc --config config.json`)? I explicitly said that you can ignore these failed installations if you don't mind about some characters being corrupted.

**Comment by TLI1233** [comment]
:o, I think it works
lemme try

**Comment by TLI1233** [comment]
THANK YOU, YOU'RE THE BEST!
IT WORKS!

**Comment by Throne3d** [comment]
:P 

If you get issues around non-English Polish characters (like in "Użytkownicy"), that's what would have been resolved by fixing this error.

For now I think this is resolved.

**Comment by TLI1233** [comment]
Can I use the same bot on 2 discords or do I have to have 2 separate bots?

**Comment by Throne3d** [comment]
I think you can use the same one. If the two different discord servers have channel names that collide (e.g. they both have a `#general` channel), you need to use the channel ID instead of the channel name. Further details would be found in [the Configuration section of the README](https://github.com/reactiflux/discord-irc#configuration)
