### ISSUE TITLE
Can I remove Authorname by discord format??

### ISSUE THREAD

**Issue by KinaiPCP** [reactiflux/discord-irc#337]
e.g : `**<NAME>** Text`
is it possible to remove **<NAME>**???

**Comment by Throne3d** [comment]
Uh. Yes? The [example configuration](https://github.com/reactiflux/discord-irc#example-configuration) specifically has a section for `format` – you can enter a custom format there.

**Comment by KinaiPCP** [comment]
well, this is possible if use advanced option, right?

 `"discord": "**<{$author}>** {$withMentions}" // When sending a message to Discord`
i thought possible if edit by lib.bot.js

**Comment by Throne3d** [comment]
You should not need to edit `lib.bot.js` at all?? It's in the `conf.json`.

**Comment by Throne3d** [comment]
You can modify that format. Like. However you want. Such as to `"discord": "{$withMentions}"`. Which is what it sounds like you want.

**Comment by KinaiPCP** [comment]
wohh Thanks @Throne3d ^_^
