### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by haxxus** [reactiflux/discord-irc#341]
> discord-irc@2.5.0 build /discord-irc
> babel lib --out-dir dist

sh: babel: command not found

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! discord-irc@2.5.0 build: `babel lib --out-dir dist`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the discord-irc@2.5.0 build script 'babel lib --out-dir dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discord-irc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel lib --out-dir dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord-irc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discord-irc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /discord-irc/npm-debug.log
[root@vultr discord-irc]# npm -v
3.10.10
[root@vultr discord-irc]# node -v
v6.12.0

**Comment by Throne3d** [comment]
Did you do `npm install` first?

**Comment by haxxus** [comment]
install gives me this :(
[root@vultr discord-irc]# sudo npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN discord.js@11.2.1 requires a peer of bufferutil@^3.0.2 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
npm WARN discord.js@11.2.1 requires a peer of node-opus@^0.2.6 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of libsodium-wrappers@^0.5.4 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of uws@^0.14.5 but none was installed.

**Comment by Throne3d** [comment]
Those are all warnings you can ignore. They're due to the upstream `discord.js` library.

I don't think you needed to prefix that command with `sudo`.

If you try running the build, now, does that work?

**Comment by haxxus** [comment]
npm run build gives me the first problem 👍 

[root@vultr discord-irc]# npm run build

> discord-irc@2.5.0 build /discord-irc
> babel lib --out-dir dist

sh: babel: command not found

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! discord-irc@2.5.0 build: `babel lib --out-dir dist`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the discord-irc@2.5.0 build script 'babel lib --out-dir dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discord-irc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel lib --out-dir dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord-irc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discord-irc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /discord-irc/npm-debug.log

**Comment by Throne3d** [comment]
Have you tried prefixing it with `sudo`? Or alternatively re-running `npm install` without the `sudo`?

If that fails, try deleting the `node_modules` folder, re-running `npm install` (without sudo), and then re-running `npm run build` (again without sudo).

**Comment by haxxus** [comment]
did it , same error as before on build

**Comment by Throne3d** [comment]
What distro are you on? Can you put what `npm bin` outputs into your path, then try the build again? It seems like it might not be able to locate the binaries in `./node_modules/.bin` properly.

**Comment by haxxus** [comment]
CentOS 7 x64
