### ISSUE TITLE
Feature Request: Transfer IRC channel topic to Discord

### ISSUE THREAD

**Issue by acerspyro** [reactiflux/discord-irc#346]
We often post updates and useful links (such as forum activation codes) in our IRC topic line, it would be extremely useful if the bot could take that topic and slap it on the Discord channel's topic with the appropriate permission.

**Comment by Throne3d** [comment]
This has already been requested in #220 and not yet implemented – there was some question over whether it was necessary, which if enough people want it will probably be obviated. I'll close this issue as a duplicate in favor of that one (but you can comment there if you want to continue the discussion).
