### ISSUE TITLE
Feature Request: command to check if nickname is online in IRC/Discord

### ISSUE THREAD

**Issue by Kovaelin** [reactiflux/discord-irc#347]
Since we can't actually see who's on the other side of the bridge unless they talk, would it be possible to ping a user from the other end and have the bot give you a status check? Thanks.

**Comment by Throne3d** [comment]
(It seems like this sort of thing was rejected last time it was suggested – #287 – with commands being out of the scope of the project.)

**Comment by Kovaelin** [comment]
What if instead of a command, there's just an "asterisk*" next to an "@nickname" that doesn't match on the other side? There's already something that exists that adds the Discord identification numbers if coming over from IRC, so maybe something similar can be done?

**Comment by Throne3d** [comment]
I'm not sure what you mean – wouldn't that only be visible on the _IRC_ side, which would defeat the point? I don't think this would give any feedback to a user on Discord checking for a user on IRC, or vice versa, since we can only edit the message we mirror across.

**Comment by FredrIQ** [comment]
One way I could see making this work is for the bot to have a message that it constantly edits -- the idea being for that message to be pinned, so that anyone could easily look at that list.

**Comment by Throne3d** [comment]
I'll close this issue for now, as commands still seem out of scope of what the bot currently does, and I'm not implementing new features. Thanks for the interest!
