### ISSUE TITLE
Authorize access to my account does not proceed

### ISSUE THREAD

**Issue by Sebastiaan25** [reactiflux/discord-irc#348]
![capture](https://user-images.githubusercontent.com/35193206/34649760-cd9527ee-f3bd-11e7-84b1-8cc84e0dbc5e.PNG)

My bot that tried to give access to my account does not want to go further than the picture, can anyone please explain or give me a reason why it's doing this.. uhmm It does not want to Authorize and doesn't give me an error or anything, it just gives me this screen?

**Comment by ekmartin** [comment]
Think we'll need some more information to help you here - does this still happen?
