### ISSUE TITLE
Disconnection with no reconnection. Sometimes only relaying in one direction.

### ISSUE THREAD

**Issue by JoinedSenses** [reactiflux/discord-irc#351]
Running from Win10
node -v 8.9.1
npm -v 5.5.1

(node:6196) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'options' of undefined
(node:6196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JoinedSenses** [comment]
To expand on this, I ran this on a fresh install of linux and a similar error occured.

(node:3093) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at item.request.gen.end (/home/arron/discord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:69:75)
    at then (/home/arron/discord/node_modules/snekfetch/src/index.js:204:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:3093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bothoem** [comment]
I experience the same problem (on Arch Linux ARM)
Discord -> IRC works fine, IRC to Discord stops working>
These are my errors:

`
(node:397) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at item.request.gen.end (/home/parabool/builds/discord-irc/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:69:75)
    at then (/home/parabool/builds/discord-irc/node_modules/snekfetch/src/index.js:204:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:397) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by Throne3d** [comment]
This looks like a duplicate of #342.

Based on the outputs here, it looks like an issue with an upstream library. We could try updating them and releasing a patch version (with a fix to joining password-gated channels), @ekmartin?

**Comment by ekmartin** [comment]
Yeah, good idea @Throne3d. Released version 2.5.1 with upgraded dependencies - please give it a try.
