### ISSUE TITLE
Problem linking one irc channel to multiple discord channels

### ISSUE THREAD

**Issue by cheesits456** [reactiflux/discord-irc#353]
i want to link one IRC channel to 3 discord channels, but it only sends it to one.  My json config is

```json
[
 {
  "nickname": "Discord",
  "server": "irc.geekshed.net",
  "discordToken": "token goes here, not gonna post it for obvious reasons",
  "channelMapping": {
   "376218653429071886": "#hangout-server",
   "403336682046357509": "#hangout-server",
   "403485350833684481": "#hangout-server"
  },
  "format": {
   "ircText": "[{$displayUsername}] {$text}",
   "urlAttachment": "[{$displayUsername}] {$attachmentURL}",
   "discord": "`IRC` **[{$author}]** {$withMentions}"
  },
  "ircNickColor": true,
  "ignoreUsers": {
   "discord": ["Hangout Bot"]
  }
 }
]
```

Even though all three discord channels are linked, it only sends to one of them.
Another problem is that ignoreUsers isn't working even though 'Hangout Bot' is the _exact_ nick of the user I want to ignore

**Comment by ekmartin** [comment]
Yeah, this isn't really supported - discord-irc creates an object for both sides of the mapping, so only unique values work. I'm not sure if it really makes sense as a feature for a two way bridge either way though, wouldn't it be a bit weird for people in the Discord channels to only be able to see half of the conversation (i.e. they won't see the messages posted to the other Discord channels).

I'll close this, but happy to re-open if more people need this as a feature in the future.
