### ISSUE TITLE
Need Help sending message to IRC

### ISSUE THREAD

**Issue by MBurchard** [reactiflux/discord-irc#354]
I've setup the BOT hopefully correct.

	info: Connected to Discord
	info: Connected to IRC
	error: Received error event from IRC prefix=OGN5.OnlineGamesNet.net, server=OGN5.OnlineGamesNet.net, command=err_cannotsendtochan, rawCommand=404, commandType=error, args=[Skynet-BOT, #skynet, Cannot send to channel]
	error: Received error event from IRC prefix=OGN5.OnlineGamesNet.net, server=OGN5.OnlineGamesNet.net, command=err_cannotsendtochan, rawCommand=404, commandType=error, args=[Skynet-BOT, #skynet, Cannot send to channel]
	error: Received error event from IRC prefix=OGN5.OnlineGamesNet.net, server=OGN5.OnlineGamesNet.net, command=err_cannotsendtochan, rawCommand=404, commandType=error, args=[Skynet-BOT, #skynet, Cannot send to channel]

The Bot sends Messages from IRC to Discord, this works perfectly.

But when I type something in the Discord Channel I see the error Messages.
The Channel is open everybody is allowed to send something to this IRC channel...

How can I find out, what's wrong?

**Comment by variablenix** [comment]
You may need to enable debug to see additional info why this is happening.

https://node-irc-upd.readthedocs.io/en/latest/API.html#irc.Client

**Comment by Throne3d** [comment]
That definitely suggests the IRC client is receiving an error (from the IRC server itself) when it tries to send a message.

I'm not sure if debug will help here – you'll need to figure out, somehow, why the IRC server won't permit you to speak in that channel. The numeric code 404 is apparently "[s]ent to a user who does not have the rights to send a message to a channel".

If you do enable debug, there may be information when the client is _joining_ the server. Perhaps it recognizes it as a bot, or it's hosted from some IP range that the server has prevented from sending messages?

**Comment by ekmartin** [comment]
I'll close this since it sounds like it's a network/channel issue.
