### ISSUE TITLE
Writing off your bot...

### ISSUE THREAD

**Issue by LAMGE2** [reactiflux/discord-irc#362]
How people write something from their bot?

![image](https://user-images.githubusercontent.com/17748621/35780462-cc9d22c0-09ec-11e8-8f42-d1ca87fd7263.png)

**Comment by Throne3d** [comment]
… This doesn't look related to this project? You want to be looking at Discord's API.

**Comment by LAMGE2** [comment]
Okay

**Comment by LAMGE2** [comment]
I could not find anything.

**Comment by Throne3d** [comment]
You need to write your own code to connect to the Discord API and send a message as a specific bot. That is not what this project is for? I don't understand why you are asking here.
