### ISSUE TITLE
Possible to assign Username/Realname to bot?

### ISSUE THREAD

**Issue by bswaldmann** [reactiflux/discord-irc#369]
I've been trying to use the bot on Rizon, and the fact that username, nick, and realname are so similar are triggering their flood detection and banning it. When I change the nick, that just changes the username and realname to match. Help?

**Comment by Throne3d** [comment]
As in the README, you can pass options to the IRC side of things using an `"ircOptions"` hash in the config file – it takes attributes as listed here: https://node-irc-upd.readthedocs.io/en/latest/API.html#irc.Client

The `userName` and `realName` options should do what you want.
