### ISSUE TITLE
Stop relaying Discord -> IRC

### ISSUE THREAD

**Issue by DvnBthlo** [reactiflux/discord-irc#373]
Hello, how can i stop relaying Discord message to IRC ? - Only read message from IRC and write to discord

**Comment by DoNotSpamPls** [comment]
The easiest solution would be to just deny Send Messages in the Discord channel (except to the bot)

**Comment by ekmartin** [comment]
No, sorry—there's no way to currently do this. I'm not sure if adding a configuration option is the right thing to do here either, so I'll close this for now. Feel free to follow @DoNotSpamPls's suggestion and implement it in a fork though!
