### ISSUE TITLE
Suffix webhook nicknames with (IRC)

### ISSUE THREAD

**Issue by ekmartin** [reactiflux/discord-irc#377]

**Comment by Throne3d** [comment]
This needs to make sure not to break the avatar matching in the current setup.

It might also not be necessary. I think messages sent through webhooks in this manner have the `BOT` tag suffixed on the username, which might make this clear enough.

**Comment by ekmartin** [comment]
I don't feel too strongly about it either way, but I do think it could be a bit confusing for users that aren't aware of the IRC bridge. With that being said, I'm not sure if `(IRC)` will help that much at all in that case though, so let's leave it for now.
