### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Sans999** [reactiflux/discord-irc#379]
Please Help Me. When I Do This:const Discord = require("discord.js");
const TOKEN = ("my token. i choose not to show it");
const PREFIX = "-"
var bot = new Discord.Client();
bot.on("ready", function() {
    console.log("TSCBot is Online!");
});
bot.on("message", function(message) {
    if (message.author.equals(bot.user)) return;
    if (!message.content.startsWith(PREFIX)) return;
    var args = message.content.substring(PREFIX.length).split(" ");
    switch (args[0].toLowerCase()) {
        case "ping":
            message.channel.sendMessage("pong!");
            break;    
        case "space":
            message.channel.sendMessage("https://forcetoknow.com/wp-content/uploads/2014/01/meteor-shower-forcetoknow.com_.jpg");
            break;
        case "embed":
            var embed = new Discord.RichEmbed();
            .setDescription("HHH");
            message.channel.sendEmbed(embed);
            break;
            default:
            message.channel.sendMessage("**Invalid command**")
    }
});
bot.login(TOKEN);
then run it, i get this: /home/sans/Desktop/DiscordBot/index.js:21
            .setDescription("HHH");
            ^

SyntaxError: Unexpected token .
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)  PLEASE HELP ME :(

**Comment by Throne3d** [comment]
The error seems to point to the exact problem? You have a separate line saying `.setDescription("HHH");`, which doesn't make sense.

**Comment by ekmartin** [comment]
This doesn't seem to be related to discord-irc either!
