### ISSUE TITLE
Use avatar for IRC user

### ISSUE THREAD

**Issue by syrm** [reactiflux/discord-irc#383]
Hello,

When user is only on IRC and not at all on discord they don't have avatar.
Maybe we should use "http://avatars.adorable.io/" for this case ?

**Comment by Kovaelin** [comment]
All users on the IRC side that aren't in Discord are automatically assigned the webhook avatar.

**Comment by syrm** [comment]
It can be customized

**Comment by Kovaelin** [comment]
Yes, that's what I'm telling you.

**Comment by syrm** [comment]
And the ability to use other service with configuration (https://robohash.org)

**Comment by syrm** [comment]
Last line of getDiscordAvatar : 
return "https://robohash.org/" + nick + "?set=set4"
instead of : 
return null;

**Comment by ekmartin** [comment]
If anyone wants to give this a go: slack-irc—which this is based on—does exactly this, through a configurable `avatarURL` [parameter](https://github.com/ekmartin/slack-irc/blob/master/lib/bot.js#L44-L46). It defaults to Adorable Avatars, but RoboHash would probably be a good choice too 👍
