### ISSUE TITLE
Better parsing emoji

### ISSUE THREAD

**Issue by syrm** [reactiflux/discord-irc#384]
Hello,

Some emoji are printed like that on IRC : `<a:in_love:432887860270465028>`
I think it should be : `:in_love:`

**Comment by Throne3d** [comment]
It looks like the `a` prefix is for animated emoji, if [Emoji.toString() in discord.js](https://github.com/discordjs/discord.js/blob/e5bd6ec150baee5ee4ca0830b80753b7c59f4844/src/structures/Emoji.js#L195) is anything to go by.

I've done a pull request – #388 – which should fix this.
