### ISSUE TITLE
Bot losing connection to close putty

### ISSUE THREAD

**Issue by marcosbucarte** [reactiflux/discord-irc#394]
I'm testing the bot on a linux server, however I noticed that when I close the putty the bot disconnects,

this should not happen since the irc server remains online, just the bot that disconnects, is there any way to keep it online even with putty closed?

**Comment by Kovaelin** [comment]
Generally, processes stop when you close the console. It doesn't have anything to do with whether the IRC server remains online, which I'm assuming you're not the one hosting. Depending on your host (who are you using?), you may be able to run screen or nohup.

**Comment by marcosbucarte** [comment]
screen worked thanks.
