### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by marcosbucarte** [reactiflux/discord-irc#397]
Well in my discord when receiving IRC message does not show Unicode characters, my encoding of my language is ISO-8859-1, even adding enconding in config. json. 

I'm doing test using characters like á,é,ó, among others;

irc conf:

```
"ircOptions": { // Optional node-irc options
      "floodProtection": false, // On by default
      "floodProtectionDelay": 1000, // 500 by default
      "encoding": "ISO-8859-1"
},
```
Image of what is shown in discord

![test1](https://user-images.githubusercontent.com/38480564/39677486-12a563b6-5152-11e8-94ff-a0b1e6ac8949.png)

**Comment by tenleftfingers** [comment]
Hi marco, I'm having the same issue. Typing accented characters like á, é, í, ó & ú in IRC show on Discord as a, e, i, o & u. Have you found a solution?

**Comment by Throne3d** [comment]
Is this still an issue with discord-irc version 2.6.2?

**Comment by Throne3d** [comment]
Closing due to lack of info.
