### ISSUE TITLE
IRC images for discord.

### ISSUE THREAD

**Issue by SombraRO** [reactiflux/discord-irc#398]
Is there any way for images sent from IRC to the discord instead of showing the link in the discord show only the image without the link?

Currently the bot it only shows the image link, if it is sent from IRC to the discord, the idea here is to allow a setting for the discord to display only the image and remove the link. Example

**Current format:** 

https://www.oficinadanet.com.br/imagens/post/14921/windows-icone.png Message sent by the user

**Proposed format:**

![windows-icone](https://user-images.githubusercontent.com/39016868/39882884-8cfac65e-545b-11e8-816d-8740fdf84df5.png)  Message sent by the user

**Comment by Throne3d** [comment]
I'm pretty sure Discord doesn't support this format, so it wouldn't be possible.

The following format might be possible, if we could make it into an embed, but I don't think I like the idea (specifically this would be two messages – one with the image embedded, and then one with the rest of the text):

![windows-icone](https://user-images.githubusercontent.com/39016868/39882884-8cfac65e-545b-11e8-816d-8740fdf84df5.png)
Message sent by the user

**Comment by SombraRO** [comment]
@Throne3d So I tested today when sending the IRC to the discord shows only the link does not open the image.

Already in this text option I thought about the question of someone sending to the discord a message and the link then I thought of an option to remove the link. It would be enabled in config.json

**Comment by Throne3d** [comment]
You must have a configuration option disabled on Discord, then. If you go to User Settings, then to "Text & Images", and allow images when posted as links to the chat, it should fix it. I just tested this in Discord, both with and without webhooks, and the link you gave definitely shows as an embed:

![image](https://user-images.githubusercontent.com/577128/39896213-239bbbce-54a5-11e8-883b-b128d09dde93.png)

**Comment by SombraRO** [comment]
@Throne3d  The permission of my bot was missing, but still could not exist an option for the administrator to choose for the bot show the link or not of images?

This would allow you to do some things in channels that only the administrator has access to and is password protected, avoiding the problems you mentioned

**Comment by Throne3d** [comment]
I suppose the functionality could exist? It seems like a weird extension to the current code, since the current code seems mostly aimed at bridging messages accurately, and I don't think many people would want to use it. @ekmartin, opinions?

**Comment by ekmartin** [comment]
No, I agree — I think it's fine to leave this to Discord's own link preview. Thank you for the suggestion though!
