### ISSUE TITLE
Reconnect on ping timeout

### ISSUE THREAD

**Issue by Deph0** [reactiflux/discord-irc#4]
discord (~discord@ip) has quit (Ping timeout: 378 seconds) :(

node is still running on screen, but has quit irc- would be nice if it could reconnect to the irc channel/server.

Perhaps printing things to console such as errors and whatnot help to see what happened / make it more visible that it's still online and doing things?

**Comment by ekmartin** [comment]
Yep, I agree. Thought node-irc did this by default, but seems like you have to pass retryCount manually when [connecting](http://node-irc.readthedocs.org/en/latest/API.html?highlight=reconnect#Client.connect).

If you export the environment variable `NODE_ENV` as `development` you'll see a lot more debug messages. If you want node-irc logs too you can set `debug` to true in `ircOptions`:

```json
"ircOptions": {
  "debug": true
}
```

**Comment by Deph0** [comment]
Ah- I've added these too, while I'm at it.
```javascript
  "ircOptions": {
      "debug": true,
      "showErrors": true,
      "autoRejoin": true,
      "autoConnect": true
  }
```

Will report back if anything happens. Cheers!

**Comment by Deph0** [comment]
Well, it timed out again, as per messages on node, it still tires to send to irc, since it picks up on text from discord.

**Comment by Deph0** [comment]
Hi again, I seem to have a much more stable connection now, however- a funny thing happened, 
the discord side went offline (but still online on irc), but still sent messages from irc to discord, but not the other way around. Lack of synchronization ?

**Comment by ekmartin** [comment]
It might be a bug in [discord.js](https://github.com/hydrabolt/discord.js/). Discord doesn't have an official API yet, so it's using their internal undocumented API.

**Comment by ekmartin** [comment]
Sorry about the delay, IRC connections should be reconnected in 0.8.2. This might have fixed your Discord issue too, more information in #25.
