### ISSUE TITLE
Invalid or Unexpected Token 

### ISSUE THREAD

**Issue by frustratedatthis** [reactiflux/discord-irc#407]
I have followed a very short and easy guide to creating a command on a discord server using a bot. I have done as the guide said and at the very end, it says "Invalid or Unexpected Token". I have retyped and downloaded the newest update of nodejs and I don't know what I am doing wrong. The link for the guide is this: https://anidiots.guide/getting-started/getting-started-long-version
and the java I have typed is below. 
PS C:\Users\TheBeastZ\Desktop\SoggyBot> npm init -y
Wrote to C:\Users\TheBeastZ\Desktop\SoggyBot\package.json:

{
  "name": "SoggyBot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

PS C:\Users\TheBeastZ\Desktop\SoggyBot> npm i -s discord.js
+ discord.js@11.3.2
added 8 packages from 7 contributors and audited 8 packages in 2.232s
found 0 vulnerabilities

So far, so good. But then I go into the JavaScript CodeEditor, Atom and copy and paste this as the guide says to: 
const Discord = require("discord.js");
const client = new Discord.Client();
​
client.on("ready", () => {
  console.log("I am ready!");
});
​
client.on("message", (message) => {
  if (message.content.startsWith("ping")) {
    message.channel.send("pong!");
  }
});
​
client.login("NDUxOTM3MjY5NDc4MTk1MjAx.DfJcnQ.Rxoffai3Qhy0k5gSvNLI-ONaxpU");

I save this under mybot.js (and of course I will change my token after posting this) then I go back to my CLI and type this: 
PS C:\Users\TheBeastZ\Desktop\SoggyBot> node mybot.js

THEN, it comes up with the error as follows: 
C:\Users\TheBeastZ\Desktop\SoggyBot\mybot.js:3
​
^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)

I am not sure what to do and it probably is the smallest thing as to why it won't work, but I am clueless and need help. Thank you so much!!

**Comment by ekmartin** [comment]
It seems like you're trying to use [discord.js](https://github.com/discordjs/discord.js) and not discord-irc, so I'd suggest asking there instead! 

With that being said, if there's no syntax errors in your code like the error complains about, it might be worth trying to upgrade your Node.js version, in case you're using a really old version without support for e.g., `const`.
