### ISSUE TITLE
when attempting to update discord-irc i get the following errors 

### ISSUE THREAD

**Issue by dmodoomsirius** [reactiflux/discord-irc#415]
https://pastebin.com/2AbbUBqw

Centos version: CentOS Linux release 7.5.1804 (Core)
NodeJS version: nodejs-6.14.2-1.el7.x86_64
Npm version : npm.x86_64 1:3.10.10-1.6.14.2.1.el7

**Comment by Throne3d** [comment]
These are warnings, not errors, and come from the upstream [https://github.com/discordjs/discord.js#optional-packages](discord.js's optional dependencies). They can be safely ignored.
