### ISSUE TITLE
This profile picture is not being picked up in webhook chats

### ISSUE THREAD

**Issue by bmintz** [reactiflux/discord-irc#420]
## Abstract
A certain blue-colored pfp is not being picked up between IRC and a webhook.

### Steps to reproduce 
1. Set your username to "foo"
2. Set your IRC nickname to "foo"
3. Set up a webhook.
4. Change "foo's" avatar in Discord [this image](https://user-images.githubusercontent.com/538336/42978164-0ad60d56-8b91-11e8-9baa-b9ae233bab1d.png).
5. Say something in IRC

### Expected behavior
username of the webhook message is foo, and the profile picture is the attached image.

### Actual behavior
username of the webhook message is foo, and the profile picture is blank.

### Comments
this is such a weird bug lmao

**Comment by RoboMWM** [comment]
These sorts of things are usually the fault of discord's client. I've had issues where the webhook's username, when clicked (not as it appears in chat), uses the "first" username sent through it to IRC for whatever reason.

**Comment by Throne3d** [comment]
I don't think I have enough information to reproduce this (it doesn't seem to reproduce straightforwardly), and this was opened a while ago, so I'm going to close it. If it reproduces (especially if you can figure out why webhooks work most of the time but not here), I would appreciate more information!
