### ISSUE TITLE
Auth and +r channels

### ISSUE THREAD

**Issue by AcidWeb** [reactiflux/discord-irc#426]
Bot don't wait for end of authorization process and that makes it impossible to use with +r channels.

**Comment by Mikaela** [comment]
Have you thought about enabling SASL in your bots so they get identified to NickServ before getting connected to the network? Sasl, username and password from https://node-irc-upd.readthedocs.io/en/latest/API.html#irc.Client if I recall correctly.

Another option would be `mode +b $~a` to ban unidentified users and `mode +e` the bot.

**Comment by AcidWeb** [comment]
SASL is correct answer to this problem.
