### ISSUE TITLE
Delay channel join until after AUTH NickServ on freenode

### ISSUE THREAD

**Issue by wstearns** [reactiflux/discord-irc#428]
Not sure this is a bug, but an annoyance.  Freenode's NickServ takes some time to +r the bot, so much so that the bot is not authenticated until after it tries to join the channel.  Is there a way to sleep or wait for NOTICE to come back before channel joining or is there a way to retry channel join after a period of time.  I don't see anything in the code for this.  I've been manually inviting the bot to the channel in the meantime.

**Comment by Mikaela** [comment]
I think this is a duplicate of https://github.com/reactiflux/discord-irc/issues/426#issuecomment-410160092 and there is also your solution.

**Comment by wstearns** [comment]
Thanks, I'll switch it.
