### ISSUE TITLE
Specify irc port in config?

### ISSUE THREAD

**Issue by nand2xor** [reactiflux/discord-irc#434]
In the standard example config there's only the server address/name. I see no parameters to add any custom port. The server I try to connect to only uses port 6697 with ssl.

So when I try to run my discord bridge, it only connect to the discord. And then nothing happens, no output or information whether or not irc is connected.

Is there any more detailed documentation for the config.json?

**Comment by Mikaela** [comment]
https://github.com/reactiflux/discord-irc/issues/425#issuecomment-408351588 (and https://github.com/reactiflux/discord-irc/issues/308 & https://github.com/reactiflux/discord-irc/issues/76)

**Comment by ekmartin** [comment]
Thanks @Mikaela — `ircOptions.port` is the way to go.
