### ISSUE TITLE
Not connecting to Foomatic IRC server

### ISSUE THREAD

**Issue by tenleftfingers** [reactiflux/discord-irc#437]
The port for this server is 6697. My config is below. Is this a situation that discord-irc doesn't handle at the moment or is my config just not right? Here is the debug log:

> 18 Sep 21:53:25 - Network error: Error: connect ECONNREFUSED 178.79.176.77:6697
> 18 Sep 21:53:25 - Connection got "close" event
> 18 Sep 21:53:25 - Disconnected: reconnecting
> 18 Sep 21:53:25 - Waiting 2000ms before retrying
> 18 Sep 21:53:27 - Attempting socket connection to IRC server

And here is the config file:

```
[

 //basic bot config for now. Once working we can explore more exotic options.
 {
  "nickname" : "BridgeHelper",
  "server" : "anchor.foonetic.net",
  "ircOptions" : {
    "port": 6697,
    "channels": "#myircchannel",
    "secure": "true",
    "showErrors": "true",
    "debug": "true"
   },
  "discordToken" : "#########",
  "channelMapping" : { "#test": "#myircchannel" }
 }
]
```

My IRC client (irssi) connects fine with the below config, so I know these settings are correct:

```
{
    address = "anchor.foonetic.net";
    chatnet = "Foonetic";
    port = "6697";
    use_ssl = "yes";
  }
```

**Comment by ekmartin** [comment]
Hi! It looks like the certificate is expired (or at least that's the error I'm seeing), so you're gonna have to set `"selfSigned": true` and `"certExpired": true` for it to connect (inside `ircOptions`).

As it connects successfully with those options from here I'll close this. Let me know if you have any more issues! 

We could probably handle this in a better way in the bot though, perhaps suggest it as an option when we see the error.

**Comment by ekmartin** [comment]
For reference, here's the config I used:

```json
[
 {
  "nickname" : "BridgeHelper",
  "server" : "anchor.foonetic.net",
  "ircOptions" : {
    "port": 6697,
    "channels": "#myircchannel",
    "secure": true,
    "selfSigned": true,
    "certExpired": true,
    "showErrors": true,
    "debug": true
   },
  "discordToken" : "#########",
  "channelMapping" : { "#test": "#myircchannel" }
 }
]
```

**Comment by ekmartin** [comment]
You also don't need the `channels` property inside `ircOptions`.
