### ISSUE TITLE
Is it possible to have a user as a target channel on IRC?

### ISSUE THREAD

**Issue by ClobberXD** [reactiflux/discord-irc#443]
Greetings! I've found this discord-irc bridge to be very useful. I'd like to extend its functionality by linking it to another user (bot, in my case), by means of QUERY in place of a proper IRC channel.

Is it possible to achieve this? If yes, how? Thanks!

**Comment by Throne3d** [comment]
This was actually asked over in another issue, <https://github.com/reactiflux/discord-irc/issues/280>, where it was determined to be out of scope. I followed up with @RheaAyase separately, and iirc, with just a couple of tweaks, the bot largely functioned okay. I expect you'd be better off asking them for more concrete information about it.
