### ISSUE TITLE
Can't Get Config to work right

### ISSUE THREAD

**Issue by hollowomnicron** [reactiflux/discord-irc#450]
I've Tried everything i could think of to fix it, but i can't get the config.json to be correct

Everytime i run npm start -- --config config.json

It fails with this

![image](https://user-images.githubusercontent.com/35974849/48975360-6354b580-f03c-11e8-90dd-7eba7bd32568.png)

Could Someone look at my config.json if  i email it to them or post it here (with tokens and passwords marked out)

**Comment by Throne3d** [comment]
Like it says in the error, your JSON file contains invalid JSON. Please validate it online, and fix the issues given by a tool such as <https://jsonlint.com/>.
