### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by Trojaner** [reactiflux/discord-irc#456]
Hey, is it possible to add docker support?

https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

**Comment by JimTheCactus** [comment]
There are several docker containers on the hub already. I haven't tried any of them, but a quick Google search turns up https://hub.docker.com/r/3stadt/reactiflux-discord-irc/

**Comment by Trojaner** [comment]
These inoffical ones are often outdated and seldom receive updates.

**Comment by JimTheCactus** [comment]
You could abduct the docker file from one of yhr other implementations and build the container from the latest source. If one is particularly good, a PR would be easy enough to get it in the repo.

Or is the intention to add it to the CD workflow?

**Comment by Trojaner** [comment]
I agree, the one in the implementation you provided looks good, it should be integrated into this repository. However, it does not contain any license which means that we need explicit permission from @3stadt

**Comment by 3stadt** [comment]
Hey guys,

I've added a license file to the repo at https://github.com/3stadt/reactiflux-discord-irc

It's an unlicense, so you are free to use it for any purpose. :)

**Comment by Trojaner** [comment]
I was just going to make a PR with 3stadt's Dockerfile but noticed that already one exists: https://github.com/reactiflux/discord-irc/pull/421

As it looks like the package owners did not merge it yet.
