### ISSUE TITLE
Parse channels similar to how names are parsed

### ISSUE THREAD

**Issue by GreenXenith** [reactiflux/discord-irc#460]
`@JohnDoe#1337` is turned into a user mention, channels (`#example`) should be turned into channel links.

**Comment by Throne3d** [comment]
Doesn't discord do this automatically? What issue are you having that you expect this to solve?

**Comment by GreenXenith** [comment]
When a message with `#channel` is sent from IRC, Discord doesn't seem to do anything with it.
The bot using this is not mine, the owner referred me to here to open an issue, though I thought initially that this was a problem with the bot, not discord-irc.

**Comment by Throne3d** [comment]
Hm, historically `#channel` has always been converted into a link by Discord, automatically – I've used it from the IRC side for a significant amount of time. Maybe Discord changed something?

When you say a bot's doing this, is it definitely using discord-irc, and not discord.js? Also, does the channel name in question contain any special characters (like accented letters)?

**Comment by luk3yx** [comment]
I think this is the problem:

When trying to send `#general` to Discord (to a guild/server where `#general` definitely exists), it is not automatically converted to a link.

![](https://screenshotscdn.firefoxusercontent.com/images/c08ae6ac-0f04-4cda-b6cb-8afc242f905f.png)


![Discord screenshot without a channel link](https://screenshotscdn.firefoxusercontent.com/images/1870fc35-fc4e-4319-b03d-75a03b8f8509.png)

However, if you say the channel ID (for example `<#000000000000000000>`) on IRC, it appears on Discord with a link:

![](https://screenshotscdn.firefoxusercontent.com/images/038128cc-bc65-4f85-a386-c4db85799eab.png)

**Comment by Throne3d** [comment]
Can confirm this no longer works. Not sure why – it always used to.

**Comment by Throne3d** [comment]
I've done a pull request that should fix this – #476. If you know how to, you could check out that branch and test it out in the meantime.
