### ISSUE TITLE
Can I connect using hexchat and is there a free proxy existing somewhere?

### ISSUE THREAD

**Issue by kopax** [reactiflux/discord-irc#464]
Hi everyone, I am looking for a way to connect with my IRC client (hexchat) to reactiflux.

I've read your repository, and it sounds like we need to host a proxy to be able to do that. 

1. Is there an hosted proxy anywhere we can use or do we need to host one ?
1. After configuring the proxy, I don't get how to connect to reactiflux using the IRC client, how can I do that?

Thanks in advance,

**Comment by Aim23** [comment]
Hi,
You cannot connect via irc client to this. All you need is an irc server to connect to.
This software is a "link" between an existing irc server and an existing discord server.
You're going to connect your hexchat client to that irc server where reactiflux is connected to.

hth

**Comment by kopax** [comment]
Hi and thanks for replying. I though this would be stuck forever :D 
We are hosting a znc server, which behave as a proxy between real server and our client. I believe it is a server and can be configured with this plugin. 

Do you have any idea how I could tweak znc to do this? Thanks in advance!

**Comment by ekmartin** [comment]
No, that's not what discord-irc is for. discord-irc is built to mirror a list of specific channels, not for use as a private IRC client. Sorry!
