### ISSUE TITLE
Can I use this as a single-line command interface to write to discord?

### ISSUE THREAD

**Issue by amelsen** [reactiflux/discord-irc#465]
i'm looking for a command line tool that can take an input parameter and paste it as a notification / text straight a discord/server channel.

A linux shell script would be fantastic, where I in the script for example can enter:

Username/password

Server/channel

Text

Even better, would be if I can parse text as a parameter into the shell script

./discordnotification <all the text I want to write>

..... and then it would write that into the channel I defined in the script...

Reason is.. I'm running a shell based application, that receives and sends text from a network monitor at work.
From within that application, I can set up an event, that can do various actions, based on the text it receives..
This application has a system function, that can execute a shell command in the background.. so what I'm trying to accomplish, is a setup where from that app capture specific text, and then executes an external command (the script), which then parses the specified text to the before mentioned specific server/channel.

**Comment by ekmartin** [comment]
This is completely unrelated to discord-irc. You can look at either using the Discord API [0] directly, or building something on top of e.g., discord.js [1].

[0] https://support.discordapp.com/hc/en-us/articles/212889058-Discord-s-Official-API
[1] https://github.com/discordjs/discord.js/
