### ISSUE TITLE
Bot doesn't pick up messages from other bots

### ISSUE THREAD

**Issue by wqfrqw** [reactiflux/discord-irc#471]
Is this a possible setting or easy change? When another bot relays some information etc. it does not get picked up by the discord-irc

**Comment by Mikaela** [comment]
If you are talking about a Discord bot, I think they have a restriction that bots cannot see messages from each other and there is nothing what discord-irc could do to it. If you mean NOTICEs from IRC, I think we are getting them through.

**Comment by benmp** [comment]
Does this effectively mean that two people using discord-irc cannot talk to each other since it requires each user to setup a bot in their name?

**Comment by Throne3d** [comment]
As far as I know, discord bots can see each other's messages just fine. I just tested it, actually, and discord-irc relayed a bot's message from Discord to IRC.

What context is this in? Does the bot only send embeds – colored boxes with a different font from regular text? (If so, I think we don't have support to send embeds across.)

**Comment by Kovaelin** [comment]
Is it possible for users to send commands to Discord from the IRC side? It doesn't seem to be possible with a second bot, but I'm wondering if it's possible if I use the same bot used to send messages.

**Comment by Throne3d** [comment]
Closing this for now! It looks like it might be a duplicate of #172, though.
