### ISSUE TITLE
[Feature Request] I'm interested in helping out and doing a new bot auto-reply feature

### ISSUE THREAD

**Issue by juliantrueflynn** [reactiflux/discord-irc#487]
**Feature**: When user replies to different channels with same message within time span of ~10 minutes, then bot auto-replies with polite message asking them to not cross-post.

If this sounds good, I can try doing a PR within next few weeks.

**Comment by JuanLuu** [comment]
Come my discord i want to talk with u, Juanzito#7158

**Comment by ekmartin** [comment]
Hi Julian! Thanks for filing a ticket. This sounds a little too specific for discord-irc though, and it's not really related to bridging Discord and IRC. I think you're better off building your own bot using something like [discord.js](https://discord.js.org/#/) to do this.
