### ISSUE TITLE
IRC users can ping @everyone

### ISSUE THREAD

**Issue by rubenwardy** [reactiflux/discord-irc#494]
Users on IRC can type `@everyone` to ping everyone, even when this is disabled in all the roles that a bot is a member of.

## User

![image](https://user-images.githubusercontent.com/2122943/60191096-ab82c300-982b-11e9-8601-989c423b4e77.png)

## Roles

* User is a member of Bot and Everyone, both have mention everyone disabled.
* The channel has mention everyone disabled on both Bot and Everyone.
* None of these roles have admin privileges set

### Bot role

![image](https://user-images.githubusercontent.com/2122943/60191058-9a39b680-982b-11e9-9ebc-2805448bd9c1.png)

**Comment by JRWR** [comment]
This should be on by default, in bot.js add disableEveryone: true, to 

this.discord = new discord.Client({ autoReconnect: true,

**Comment by rubenwardy** [comment]
> This should be on by default, in bot.js add disableEveryone: true, to

This doesn't work in the main channel which uses webhooks, but does work in the channel without webhooks

**Comment by rubenwardy** [comment]
here's the config:

```json
[
 {
    "nickname": "DiscordCTF",
    "server": "irc.freenode.net",
    "ircOptions": {
      "password": "",
      "sasl": true
    },
    "discordToken": "",
    "channelMapping": {
      "#server": "##minetest-ctf",
      "#staff": "#privatechan"
    },
    "webhooks": {
      "#server": ""
    }
  },

 {
    "nickname": "DiscordMTE",
    "server": "irc.freenode.net",
    "discordToken": "",
    "channelMapping": {
      "#general": "#minetestedu",
      "#resources": "#minetestedu-resources",
      "#modding": "#minetestedu-modding"
    },
    "webhooks": {
      "#general": ""
    }
  }
]

```

**Comment by doublehelix457** [comment]
Webhooks dont limit mentions to @everyone and @here. I had to manually strip out those mentions in bot.js myself.

**Comment by Kakkela** [comment]
You can add the disableEveryone in the webhook sending part of the code with this https://discord.js.org/#/docs/main/stable/typedef/WebhookMessageOptions

I can come back tomorrow to paste the working code when I have access to my box.

**Comment by Kakkela** [comment]
```
    // Webhooks first
    const webhook = this.findWebhook(channel);
    if (webhook) {
      _logger2.default.debug('Sending message to Discord via webhook', withMentions, channel, '->', `#${discordChannel.name}`);
      const avatarURL = this.getDiscordAvatar(author, channel);
      const username = _lodash2.default.padEnd(author.substring(0, USERNAME_MAX_LENGTH), USERNAME_MIN_LENGTH, '_');
      webhook.client.sendMessage(withMentions, {
        username,
        text,
        avatarURL,
        disableEveryone: true
      }).catch(_logger2.default.error);
      return;
    }
```
Here's the proper snippet for webhook sending without everyone and here mentions.

**Comment by Throne3d** [comment]
This should be fixed in the master branch now! I'll look into releasing with the change, but may not do so very soon.
