### ISSUE TITLE
[Help] Install multiple instances?

### ISSUE THREAD

**Issue by CoinCrazy66** [reactiflux/discord-irc#505]
I've got the relay working fine,  several of the questions I had while trying to install and configure I found the answers to in the closed issues :)  

Although now I'm a little lost and curious if anybody has a quick fix for installing multiple instances of the bot to ubuntu 19.04?  ,   Thanks in advance to the people posting here :)

also:  is it possible to use the example posted to https://robohash.org/  to show a different robot or bird face for users instead of the webhook link that shows their own user avatar?

**Comment by Throne3d** [comment]
Hey there! What do you mean about multiple instances? You should be able to run the discord-irc command multiple times with different config files, or use another object in the config array like the README shows, depending on what you mean. Are you trying something specific that isn't working?

With respect to the second thing, the custom webhook avatar feature (robohash etc) isn't yet in a discord-irc release, as far as I know, and within the master branch there's currently no way to override the avatars of users who appear on the discord side of things too. Is that what you're looking for? I guess we could add a config for that, but I'm not sure how much people would use it and it starts to bloat the config file a bit.

**Comment by CoinCrazy66** [comment]
I figured it out that night by creating multiple config files for multiple chans and servers :)
Also thanks for the info about robohoash.

Now I'm just curious why I'm able to get the relay to post from two discords to a single irc channel,  but it won't relay from that irc chan back to both of the discord servers, only one of them and it seems to choose the option I have second in line in the config file for which discord to post msgs to,

Everything thing else is working fine though. :)

**Comment by Throne3d** [comment]
I'll close this issue, then – the other one can be used to track this request.
