### ISSUE TITLE
Avatar changes by users are not applied when posting through webhook

### ISSUE THREAD

**Issue by cplemaster** [reactiflux/discord-irc#510]
**Applies to:**

Using webhook URLs to spoof avatars and usernames from IRC when matched to Discord usernames in the server.

**What was expected:**

User changes avatar on a whim, bot spoof should use the new avatar.

**What happened instead:**

The bot doesn't pick up the new picture, it uses the generic discord profile picture instead, until it is restarted.

Is this something that can be fixed? It's been amazing so far, but my server staff got pretty irritated just recently because someone changed their avatar and the bot started posting their messages with no profile pic. This ended up looking like spam/issues with the bot, when it seems it's just "caching" the old URL for the profile picture and isn't updating when it's changed.

**Comment by cplemaster** [comment]
![image](https://user-images.githubusercontent.com/55680698/65403161-8c8ec100-dd87-11e9-9627-3873c1ea636a.png)

Here is an example where a user tested by changing their avatar, then sending a message shortly after; the avatar change broke the avatar spoofing and made it default back to the default discord avatar.

**Comment by Miosame** [comment]
The issue was with too big avatars not displaying, regex replacing the size to be always 128x128 fixes the issue, PR: https://github.com/reactiflux/discord-irc/pull/511

**Comment by Throne3d** [comment]
I looked around and couldn't find any Discord documentation on the max size for webhook images. It seems particularly strange that it would be different from the limit for user avatars. Can you confirm that this is still an issue, it's consistently replicable by using a large avatar, and that it's fixed by reducing the size of the avatar?

**Comment by Miosame** [comment]
Updated and confirmed this is still an issue  in #511

**Comment by Throne3d** [comment]
Fixed in 88fecf3aa18fed509d6a70bc335b3b6bf11a3e2b, hopefully! Please get back to me if this is still an issue. I'll look into cutting a patch release with this change if I have time, but otherwise please try the master branch.

**Comment by coneypylon** [comment]
I had this happen to me recently - it seems like until a user messages on Discord while the bot is active, any message they send on IRC doesn't pick up the avatar (or the avatar changes)
