### ISSUE TITLE
IRC users still able to mention Discord users (by username or ID) and vice versa, even with ircPreventMention enabled

### ISSUE THREAD

**Issue by 2secslater** [reactiflux/discord-irc#517]
With the flag `ircPreventMention` set to `true`, both users from IRC and Discord are still able to mention each other from both ends. I am running the latest commit.

**Comment by jesseerwin** [comment]
I don't think you understand what that option is for. All it does it put an invisible character in the nicknames sent by the bridge to IRC so that users who talk in both Discord and IRC don't get a highlight every time they send a message in Discord.

**Comment by Throne3d** [comment]
Yeah, the function isn't to prevent cross-bridge mentions, it's to prevent _accidental_ mentions by existing in both locations at the same time. (A bunch of IRC messages going `<Throne3d> hey guys!`, when you exist in IRC as `Throne3d`, will end up pinging you lots.)

The name could probably be clearer, but we'd need to provide an alias for backwards compatibility if we change it.

**Comment by Throne3d** [comment]
Actually, never mind – since we haven't cut a release with the feature yet, I can just change the name without breaking compatibility. I'll see about renaming it `cohabitationPingFix` or something (ugly name but at least it describes the issue better).

**Comment by Throne3d** [comment]
Went with `parallelPingFix`. Closing this since the configuration name now matches better with its described behavior.
