### ISSUE TITLE
Absurd number of files

### ISSUE THREAD

**Issue by Byproduct** [reactiflux/discord-irc#532]
While migrating my server, I noticed discord-irc (as well as slack-irc) have both placed more than 10000 files (mainly node_modules) in their folders. Is this really necessary? 

Or maybe I just messed something up during install?

**Comment by Throne3d** [comment]
This is very common in node.js-based projects! I'm not sure if 10,000 exactly is the number of files I'd expect, but this project itself has upwards of 30, adds more when transpiled, and [has a very large number of dependencies when you look at the full list](https://github.com/reactiflux/discord-irc/blob/master/package-lock.json). I don't think there's anything to be done about it, but I've seen people complain that it can be a problem on filesystems where individual file operations are slow.
