### ISSUE TITLE
Mode and topic changes?

### ISSUE THREAD

**Issue by TLWXPUser** [reactiflux/discord-irc#533]
Is there any way i can show the IRC's Mode and topic changes? If not, may this be a feature request

**Comment by Throne3d** [comment]
Hey! Unfortunately this is not something you can enable in the project at the moment. I'm also now only maintaining discord-irc for bug fixes and vulnerabilities, as I'm no longer an active user of the project. Accordingly, this enhancement is not likely to be added to the project itself any time soon.

This has been requested before, in https://github.com/reactiflux/discord-irc/issues/345 (mode changes) and https://github.com/reactiflux/discord-irc/issues/220 (topic changes), so I'll close this as a duplicate for now.
