### ISSUE TITLE
JavaScript Syntax error on launch

### ISSUE THREAD

**Issue by Murkur** [reactiflux/discord-irc#545]
recently upgraded my pc to I9 and after installing the motherboard software better discord now crashes with a java script uncaught exception rerunning the installer and repairing with "javascript error on star" causes it to give the same error 
![image](https://user-images.githubusercontent.com/20288698/87863953-af4e1f80-c92f-11ea-92da-6965daaf16ea.png)

**Comment by DarkSpyro003** [comment]
Hello,
This is the issue tracker for a bot-based bridge between Discord and IRC. I believe you are looking for the BandagedBD BetterDiscord issue tracker. https://github.com/rauenzi/BetterDiscordApp/issues

**Comment by Murkur** [comment]
oh sorry friend directed me to the wrong link thank you
