### ISSUE TITLE
Numbers in Front of Names in IRC - Twitch

### ISSUE THREAD

**Issue by smashedr** [reactiflux/discord-irc#56]
It seems everyone's name from Discord, is appended with 2 numbers when being relayed into IRC.

Here is an example from IRC:

4:58 Discord_Bot: <04🎮 Mr McPowned> i was more curious on the bot's points
4:58 Discord_Bot: <09Shane> LOL
4:59 Discord_Bot: <09Shane> i know we can get nightbot in here
4:59 Discord_Bot: <09Shane> revlo's API is a WIP
5:03 Discord_Bot: <13Will> Your base are belong to us!

Not sure if this is specific to the Twitch IRC server, or has shown up elsewhere.
Is there any setting that can be enabled to fix this?

**Comment by ekmartin** [comment]
This is probably because Twitch doesn't support IRC colors. Try setting `ircNickColor` to `false` in your configuration.

**Comment by smashedr** [comment]
That did it, thanks!

**Comment by ekmartin** [comment]
Cool!
