### ISSUE TITLE
Configure IRC nick colors in config.json

### ISSUE THREAD

**Issue by KWeaver87** [reactiflux/discord-irc#560]
A followup to #224, I'd like to see a new config.json option for customizing what colors are used when `ircNickColor` is enabled.
I really like having the nick colors enabled. But some of my friends use a light background, and some of the brighter colors (yellow, light_cyan) wash out easily on their end. I've gone in and manually edited the NICK_COLORS on my server, but obviously this is not an ideal solution.

**Comment by Throne3d** [comment]
Fixed in #561!
