### ISSUE TITLE
tutorials to authorise bot are outdated 

### ISSUE THREAD

**Issue by TunnelThruTime** [reactiflux/discord-irc#570]
tutorials to set-up the bot that is used in this project are outdated.

**Comment by Throne3d** [comment]
Hey! I've updated the majority of the wiki page with new screenshots – most of them are identical or functionally equivalent, but it does now present the new consent dialog a bit more clearly. I've also removed some spam that had made its way onto the wiki, and locked it to prevent that from happening again.

Hopefully that fixes this! Thanks for bringing it up.
