### ISSUE TITLE
Nooob questions

### ISSUE THREAD

**Issue by gilbo47** [reactiflux/discord-irc#575]
Hello.  I'm trying to connect to an invite only channel - am i right in saying i need to shove my login credentials into this payload:

  "autoSendCommands": [ // Commands that will be sent on connect
      ["PRIVMSG", "NickServ", "IDENTIFY password"],
      ["MODE", "test", "+x"],
      ["AUTH", "test", "password"]
  ],

if so, do i need all 3 arrays? what do they do? and is there any chance you could provide an example?
also is there an option to connect to irc channel over port 7000 (SSL)?

Thanks!

**Comment by gilbo47** [comment]
the error i get is:

  command: 'err_inviteonlychan',
  rawCommand: '473',
  commandType: 'error',
  args: [ 'AR1', '#nameredacted', 'Cannot join channel (Invite only)' ]

We seem to need to login to the IRC only with a private key associated our ID (which i have) and a word like so:

/msg <word> enter <private key>
I'm guessing I Just need help to transpose that into the autoSendCommands list?

THanks

**Comment by gilbo47** [comment]
all sorted.  lots of trial and error and it's now working.

**Comment by Underknowledge** [comment]
:anger:  Share your story @gilbo47. I just try to do the same thing.
