### ISSUE TITLE
No way to login with a token

### ISSUE THREAD

**Issue by UberActivist** [reactiflux/discord-irc#58]
There currently doesn't appear to be a way to login to discord with a token on an API application account. :/

**Comment by abalabahaha** [comment]
Difference is basically calling `bot.loginWithToken("token");` instead of `bot.login("email", "password");`

**Comment by TheDoctorsLife** [comment]
Set discordEmail to bot ID & discordPassword to bot token, tested this and it works.

**Comment by TheDoctorsLife** [comment]
Incoming PR fixing this.
