### ISSUE TITLE
How does weechat integration work?

### ISSUE THREAD

**Issue by TDHTTTT** [reactiflux/discord-irc#592]
So I noticed in the gif at the beginning README that it shows using it in weechat. However, I couldn't find instructions on how to set up weechat integration. Could anyone point me to it?

**Comment by TDHTTTT** [comment]
Yeah I understand that. It just so happens that I have been using weechat and would love to get it working.

**Comment by SuatNguyen** [comment]
Hey, do I need to install weechat in order to make the bot work?

**Comment by z-nexx** [comment]
I think that what karx1 means is that there is no "Weechat integration", the author of the gif is simply just using the IRC client called Weechat when showing off the IRC part of the bot. You could use any IRC client such as mIRC or irssi to do the same thing.
