### ISSUE TITLE
cannot auth bot on irc

### ISSUE THREAD

**Issue by Toxicterror** [reactiflux/discord-irc#60]
on the irc network i use there is a simple command to auth a user
/authserv auth username password

how do i configure the automessages to do exactly that? none of the below mentioned actualy authenticated the bot.

["AUTHSERV", "auth username password"]
["AUTHSERV", "auth", "username password"]
["AUTHSERV", "auth", "username", "password"]
["AUTHSERV auth", "username", "password"]
["AUTHSERV auth username", "password"]
["AUTHSERV auth username password"]

no errors apearing except for the last entry which gives a 421 unknown command

**Comment by TheDoctorsLife** [comment]
Try using ```"PRIVMSG", "AuthServ", "username password"```

**Comment by Toxicterror** [comment]
_phew almost forgot about this..._

could solve it. was a problem with the authserv missing an authcookie.
got the error message displayed by activating (or commenting out the if-clause) the debug mode of discord-irc.

`if (process.env.NODE_ENV === 'development') {
_winston2.default.level = 'debug'; 
}
`

**Comment by ekmartin** [comment]
Glad you figured it out. For future debugging you can run the application with `NODE_ENV=development` in front to enable debug logs (this sets the environment variable NODE_ENV to development).

I.e. `NODE_ENV=development discord-irc --config config.json` or `NODE_ENV=development npm start -- --config config.json`.
