### ISSUE TITLE
discord.js is deprecated!

### ISSUE THREAD

**Issue by comicsansgreenki** [reactiflux/discord-irc#607]
```
npm WARN deprecated discord.js@12.3.1: no longer supported
```
Uh oh. Maybe there's a community-maintained fork?

**Comment by marissacute** [comment]
If you download and build discord-irc from Github instead of installing from npm that error goes away. Dependencies have been updated on the source but this hasn't been released to npm yet.

**Comment by comicsansgreenki** [comment]
well...looks like i left an issue open and stale here. i'll just close that real quick, myb >v<
