### ISSUE TITLE
What channel to put for discord?

### ISSUE THREAD

**Issue by siadevelopment** [reactiflux/discord-irc#67]
I had my original server working then accidentally deleted it. I configured a new install (with the new version) and I'm confused to what to put for:  "#other-discord":

I've tried the channel name (#general), and it says 
info: Tried to send a message to a channel the bot isn't in:  #general

I've registered for the API, converted it to a bot, now I'm confused. can you please help?

thanks!

**Comment by ekmartin** [comment]
Hi! If you want the bot to transfer messages between #general and an IRC channel, that's correct. 

Have you authorized the bot with your Discord server? You can do so by going to `https://discordapp.com/oauth2/authorize?&client_id=YOUR_CLIENT_ID_HERE&scope=bot&permissions=0` where `YOUR_CLIENT_ID_HERE` is replaced with the client id from your Discord application. More instructions here: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

**Comment by siadevelopment** [comment]
Thanks, I found it right after I posted this. problem solved.

**Comment by ekmartin** [comment]
👍
