### ISSUE TITLE
Any way to connect using SSL?

### ISSUE THREAD

**Issue by Gachl** [reactiflux/discord-irc#76]
Hi

I'm trying to connect discord-irc to a bouncer which runs SSL. Is there any way to do this? I have tried using "server": "localhost:+20001" which didn't seem to work.

```
> discord-irc --config discord.conf
debug: Connecting to IRC and Discord
debug: Connected to Discord
```
and then nothing happens

Thanks,
Gachl

edit: sorry I'm stupid, I didn't look at the available options site.

**Comment by BeauBouchard** [comment]
I also am wondering this. Is there a way to connect with SSL?

**Comment by Gachl** [comment]
Check the secure option here:

http://node-irc.readthedocs.io/en/latest/API.html#irc.Client

**Comment by Peppernrino** [comment]
> "secure": "true",
"port": "6697"

**Comment by Throne3d** [comment]
Better documentation link: https://node-irc-upd.readthedocs.io/en/latest/API.html#irc.Client

But yeah, you just set secure to true and make sure you set the correct port if applicable.

**Comment by Peppernrino** [comment]
lol. i was trying to figure it out at the time as well.
