### ISSUE TITLE
Changing bot-user Avatar with command

### ISSUE THREAD

**Issue by Deph0** [reactiflux/discord-irc#77]
the discord-js docu says, (the command `%docs client.setAvatar -g` on node_discord-js @ discord-api server)
```
setAvatar(avatar, callback) - Sets the avatar of the client
• avatar - Base64 Resolvable, new avatar of the client
• callback - function taking the following:
    • error - error if any occurred
```
is there a way to use this in a discord-irc command?

**Comment by Deph0** [comment]
I recived this function from the people on the discord-js chan; if it is of help, i do not know.
```javascript
request({
  method: 'GET',
  url: URL_OF_AVATAR,
  encoding: null
}, (err, res, image) => {
  if (err) return msg.client.sendMessage(msg.channel, "Failed to get a valid image.");
  
  msg.client.setAvatar(image, (err) => {
    if (err) return msg.client.sendMessage(msg.channel, "Failed setting avatar.");
    return msg.client.sendMessage(msg.channel, "Changed avatar.");
  });
});
```

**Comment by ekmartin** [comment]
No, discord-irc doesn't really have a concept of user commands. What are you trying to achieve?

**Comment by Deph0** [comment]
According to the people on discord-js, discord is assuming people to implement a way to change the bot-user avatar, since they haven't made a way to do so in the developer application page.

**Comment by Kakkela** [comment]
There is ability to change avatar in developer panel.

**Comment by Deph0** [comment]
No- that is the application icon, it is not the same as bot-user avatar. 
However, discord does set the avatar the first time after you created the application to the avatar, but if you want to change it after that, you’re screwed.

**Comment by UberActivist** [comment]
My suggestion would be to have the user put an avatar of his or her choice into the main directory and have a piece of code that assigns this avatar in the main directory as the bot's avatar. OR, you could have an avatar setting in the config file, which the user can point to what they want the avatar to be changed to, or null if they don't want it to change at all (ex they already have an avatar set).

**Comment by smashedr** [comment]
Until this suite, or any some other tool offers an avatar change API call, you can change the image with a simple cURL call.

Get: 1) base64 encoded image, 2) bot username, 3) bot oauth token.

Then you can execute this (Please note the escaping pattern below is formatted for BASH, just make sure the data is valid JSON with "username: username, avatar: avatar" key values. Also, the image has been truncated in size to fit in this post and ends with ..........):

`IMAGE='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGY..........'
TOKEN='MTk1Mzk3MDczMTcwOTg5MDU2.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx'
NAME="SuperBot"
curl --request PATCH -H "Content-Type: application/json" -H "Authorization: ${TOKEN}" -d '{"username": "'"${NAME}"'", "avatar": "'"${TOKEN}"'"}' 'https://discordapp.com/api/users/@me'`

**Comment by smashedr** [comment]
You can change your avatar here: https://blastsoftstudios.com/dac.html

**Comment by ekmartin** [comment]
This is gonna be much easier if we change to webhooks, as those allow a custom avatar for each message (then you can implement something like [this gif](https://camo.githubusercontent.com/26fea6d3b3c42fb4296a7ed22152b9b09e4dd8e5/687474703a2f2f692e696d6775722e636f6d2f3538483648674f2e676966) of slack-irc).

**Comment by lmf-git** [comment]
> You can change your avatar here: https://www.blastsoftstudios.com/dac

Are you crazy? Why would people give their bot token to you?
