### ISSUE TITLE
Turned 2k messages into 66k discord messages?

### ISSUE THREAD

**Issue by MattiSony** [reactiflux/discord-irc#79]
Soo I was able to accidentally spam my irc channel with 2000 messages within 10 seconds(oops) and somehow discord-irc tried to send it 66,006 times within 15 minutes to discord, I know this because one of the Discord devs told me about it, just wanted you to know.

**Comment by macdja38** [comment]
was this with an old build of discord-irc using a version of discord.js prior to v8?
that old version had very very bad rate limiting support and would have simply tried to send all the messages over and over and over again.

**Comment by MattiSony** [comment]
Yea, it was. Just gonna close this then, haven't happened since either.
