### ISSUE TITLE
Recognize disconnects from discord and reconnect

### ISSUE THREAD

**Issue by mcmonkey4eva** [reactiflux/discord-irc#80]
Sometimes the bot gets disconnected from Discord (probably by the net it's hosted off going down momentarily really) - it says it's "not in that channel" when this happens, when in reality it's just not connected at all. Once reconnected, it recognizes the channel and functions perfectly. It'd be wonderful if there could be some catch for this situation so I wouldn't have to restart the bot occasionally.

**Comment by ekmartin** [comment]
Are you using the latest version of discord-irc? discord.js should reconnect when it disconnects from Discord: https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L26

**Comment by mcmonkey4eva** [comment]
Okay so my net died on my house yeah again for no apparent reason for about half an hour.
There wasn't so much as an error message on either my two Discord-IRC bots. They just weren't online on Discord and didn't reconnect when given more than enough time for everything else to reconnect fine. They remained disconnected from IRC as well. The programs didn't stop running, they just stopped /doing anything/. I had to CTRL-C them and re-launch them.

I think relying on default 'autoReconnect' options is insufficient for a proper bot, there needs to be some amount of own-code checks. Can't have bots needing restarts without any indication of that fact except for the bot being entirely unresponsive to anything short of direct console access.

**Comment by mcmonkey4eva** [comment]
Today the bots were correctly loaded into Discord, but not IRC. What fun!

**Comment by ekmartin** [comment]
Hopefully this should be fixed in v2 of discord-irc, which uses v9 of discord.js - a significant rewrite.
