### ISSUE TITLE
Can't get bot to connect to discord

### ISSUE THREAD

**Issue by alaswell** [reactiflux/discord-irc#84]
Hello,

I get nothing from Discord->IRC and keep getting an error IRC->Discord:
`info: Tried to send a message to a channel the bot isn't in: #FFPickup"

I have followed everything [here] (https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token) and the bot comes online in discord and joins my channel in irc, when I run my config.json:

```
{
    "nickname": "discordRelay",
    "server": "uk.quakenet.org",
    "discordToken": "copied.over.from.app",
    "autoSendCommands": [ 
      ["MODE", "discordRelay", "+x"],
      ["AUTH", "discordRelay", "password"]
    ],
    "channelMapping": { 
      "#FFPickup": "#ff.test" 
    },
    "ircOptions": { 
      "floodProtection": false, 
      "floodProtectionDelay": 1000 
    },
    "ircNickColor": false, 

    "commandCharacters": ["!", "."]
  }
```

Any idea what I am missing?

**Comment by ekmartin** [comment]
Have you invited the bot to your Discord server? See the last steps in @TheDoctorsLife's guide here: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

**Comment by alaswell** [comment]
I did, I went to https://discordapp.com/oauth2/authorize?&client_id=YOUR_CLIENT_ID_HERE&scope=bot&permissions=0  where YOUR_CLIENT_ID_HERE is replaced with the Client ID my bot has from the APP page and I invited it. The bot idle's in the channel, I can give it permissions and everything, and when I run the config with: 

`discord-irc --config C:\Users\Lex\node_modules\discord-irc\config.json `

The bot comes online in the Discord server and joins the IRC channel, but then I can't get either to do anything past that.

**Comment by ekmartin** [comment]
Did you get it to work eventually? If not your connectivity issues might have been fixed in v2 of discord-irc.
