### ISSUE TITLE
Imperfect Discord text handling

### ISSUE THREAD

**Issue by FlashingYoshi** [reactiflux/discord-irc#86]
1. Discord to IRC messages will cut off and not extend if they run on for too long (sometimes).
2. Both Discord to IRC and IRC to Discord messages lack the proper formatting.
3. IRC do not send bot-prefixed messages to Discord as one would expect.

**Comment by DarkSpyro003** [comment]
1. should be fixed by #129 
I'm not sure what is meant by 3.

**Comment by rahatarmanahmed** [comment]
2 should be covered once #205 is merged. Believe 1 and 3 are already supported so we can probably close this.
